// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ServiceProviderDiscoveryMode service provider discovery mode
//
// swagger:model ServiceProviderDiscoveryMode
type ServiceProviderDiscoveryMode string

// Validate validates this service provider discovery mode
func (m ServiceProviderDiscoveryMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service provider discovery mode based on context it is used
func (m ServiceProviderDiscoveryMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
