// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// SystemSCIMv2GetSystemGetSCIMv2SchemaReader is a Reader for the SystemSCIMv2GetSystemGetSCIMv2Schema structure.
type SystemSCIMv2GetSystemGetSCIMv2SchemaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}] systemSCIMv2GetSystemGetSCIMv2Schema", response, response.Code())
	}
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaOK creates a SystemSCIMv2GetSystemGetSCIMv2SchemaOK with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaOK() *SystemSCIMv2GetSystemGetSCIMv2SchemaOK {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaOK{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaOK describes a response with status code 200, with default header values.

SCIMv2 SCIMv2SchemaResponse
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaOK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.SCIMv2Schema
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema o k response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema o k response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema o k response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema o k response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema o k response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema o k response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) Code() int {
	return 200
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaOK %s", 200, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaOK %s", 200, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) GetPayload() *models.SCIMv2Schema {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.SCIMv2Schema)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized creates a SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized() *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema unauthorized response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema unauthorized response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema unauthorized response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema unauthorized response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema unauthorized response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema unauthorized response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) Code() int {
	return 401
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaForbidden creates a SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaForbidden() *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema forbidden response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema forbidden response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema forbidden response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema forbidden response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema forbidden response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema forbidden response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) Code() int {
	return 403
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaForbidden %s", 403, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaForbidden %s", 403, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaNotFound creates a SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaNotFound() *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound describes a response with status code 404, with default header values.

Not found
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema not found response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema not found response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema not found response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema not found response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema not found response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema not found response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) Code() int {
	return 404
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaNotFound %s", 404, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaNotFound %s", 404, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed creates a SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed() *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed describes a response with status code 412, with default header values.

Precondition failed
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed struct {
	Payload *models.Error
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema precondition failed response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema precondition failed response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema precondition failed response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema precondition failed response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema precondition failed response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema precondition failed response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) Code() int {
	return 412
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests creates a SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests with default headers values
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests() *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests{}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this system s c i mv2 get system get s c i mv2 schema too many requests response has a 2xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get system get s c i mv2 schema too many requests response has a 3xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get system get s c i mv2 schema too many requests response has a 4xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get system get s c i mv2 schema too many requests response has a 5xx status code
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get system get s c i mv2 schema too many requests response a status code equal to that given
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the system s c i mv2 get system get s c i mv2 schema too many requests response
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) Code() int {
	return 429
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Schemas/{schemaID}][%d] systemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
