// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaParams creates a new SystemSCIMv2GetSystemGetSCIMv2SchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaParams() *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithTimeout creates a new SystemSCIMv2GetSystemGetSCIMv2SchemaParams object
// with the ability to set a timeout on a request.
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithTimeout(timeout time.Duration) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaParams{
		timeout: timeout,
	}
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithContext creates a new SystemSCIMv2GetSystemGetSCIMv2SchemaParams object
// with the ability to set a context for a request.
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithContext(ctx context.Context) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaParams{
		Context: ctx,
	}
}

// NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithHTTPClient creates a new SystemSCIMv2GetSystemGetSCIMv2SchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemSCIMv2GetSystemGetSCIMv2SchemaParamsWithHTTPClient(client *http.Client) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	return &SystemSCIMv2GetSystemGetSCIMv2SchemaParams{
		HTTPClient: client,
	}
}

/*
SystemSCIMv2GetSystemGetSCIMv2SchemaParams contains all the parameters to send to the API endpoint

	for the system s c i mv2 get system get s c i mv2 schema operation.

	Typically these are written to a http.Request.
*/
type SystemSCIMv2GetSystemGetSCIMv2SchemaParams struct {

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	// IPID.
	IPID string

	// SchemaID.
	SchemaID string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system s c i mv2 get system get s c i mv2 schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithDefaults() *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system s c i mv2 get system get s c i mv2 schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithTimeout(timeout time.Duration) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithContext(ctx context.Context) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithHTTPClient(client *http.Client) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithIfMatch(ifMatch *string) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIPID adds the iPID to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithIPID(iPID string) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetIPID(iPID)
	return o
}

// SetIPID adds the ipId to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetIPID(iPID string) {
	o.IPID = iPID
}

// WithSchemaID adds the schemaID to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithSchemaID(schemaID string) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetSchemaID(schemaID)
	return o
}

// SetSchemaID adds the schemaId to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetSchemaID(schemaID string) {
	o.SchemaID = schemaID
}

// WithXCorrelationID adds the xCorrelationID to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithXCorrelationID(xCorrelationID *string) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WithXIdempotencyKey(xIdempotencyKey *string) *SystemSCIMv2GetSystemGetSCIMv2SchemaParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the system s c i mv2 get system get s c i mv2 schema params
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *SystemSCIMv2GetSystemGetSCIMv2SchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param ipID
	if err := r.SetPathParam("ipID", o.IPID); err != nil {
		return err
	}

	// path param schemaID
	if err := r.SetPathParam("schemaID", o.SchemaID); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
