// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// NewSystemSCIMv2PatchGroupParams creates a new SystemSCIMv2PatchGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemSCIMv2PatchGroupParams() *SystemSCIMv2PatchGroupParams {
	return &SystemSCIMv2PatchGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemSCIMv2PatchGroupParamsWithTimeout creates a new SystemSCIMv2PatchGroupParams object
// with the ability to set a timeout on a request.
func NewSystemSCIMv2PatchGroupParamsWithTimeout(timeout time.Duration) *SystemSCIMv2PatchGroupParams {
	return &SystemSCIMv2PatchGroupParams{
		timeout: timeout,
	}
}

// NewSystemSCIMv2PatchGroupParamsWithContext creates a new SystemSCIMv2PatchGroupParams object
// with the ability to set a context for a request.
func NewSystemSCIMv2PatchGroupParamsWithContext(ctx context.Context) *SystemSCIMv2PatchGroupParams {
	return &SystemSCIMv2PatchGroupParams{
		Context: ctx,
	}
}

// NewSystemSCIMv2PatchGroupParamsWithHTTPClient creates a new SystemSCIMv2PatchGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemSCIMv2PatchGroupParamsWithHTTPClient(client *http.Client) *SystemSCIMv2PatchGroupParams {
	return &SystemSCIMv2PatchGroupParams{
		HTTPClient: client,
	}
}

/*
SystemSCIMv2PatchGroupParams contains all the parameters to send to the API endpoint

	for the system s c i mv2 patch group operation.

	Typically these are written to a http.Request.
*/
type SystemSCIMv2PatchGroupParams struct {

	// GroupID.
	GroupID string

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	// IPID.
	IPID string

	// Patch.
	Patch *models.SCIMv2Patch

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system s c i mv2 patch group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSCIMv2PatchGroupParams) WithDefaults() *SystemSCIMv2PatchGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system s c i mv2 patch group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSCIMv2PatchGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithTimeout(timeout time.Duration) *SystemSCIMv2PatchGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithContext(ctx context.Context) *SystemSCIMv2PatchGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithHTTPClient(client *http.Client) *SystemSCIMv2PatchGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithGroupID(groupID string) *SystemSCIMv2PatchGroupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetGroupID(groupID string) {
	o.GroupID = groupID
}

// WithIfMatch adds the ifMatch to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithIfMatch(ifMatch *string) *SystemSCIMv2PatchGroupParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIPID adds the iPID to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithIPID(iPID string) *SystemSCIMv2PatchGroupParams {
	o.SetIPID(iPID)
	return o
}

// SetIPID adds the ipId to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetIPID(iPID string) {
	o.IPID = iPID
}

// WithPatch adds the patch to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithPatch(patch *models.SCIMv2Patch) *SystemSCIMv2PatchGroupParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetPatch(patch *models.SCIMv2Patch) {
	o.Patch = patch
}

// WithXCorrelationID adds the xCorrelationID to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithXCorrelationID(xCorrelationID *string) *SystemSCIMv2PatchGroupParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) WithXIdempotencyKey(xIdempotencyKey *string) *SystemSCIMv2PatchGroupParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the system s c i mv2 patch group params
func (o *SystemSCIMv2PatchGroupParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *SystemSCIMv2PatchGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupID
	if err := r.SetPathParam("groupID", o.GroupID); err != nil {
		return err
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param ipID
	if err := r.SetPathParam("ipID", o.IPID); err != nil {
		return err
	}
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
