// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// SystemSCIMv2ListGroupsReader is a Reader for the SystemSCIMv2ListGroups structure.
type SystemSCIMv2ListGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemSCIMv2ListGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemSCIMv2ListGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSystemSCIMv2ListGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSystemSCIMv2ListGroupsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSystemSCIMv2ListGroupsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSystemSCIMv2ListGroupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewSystemSCIMv2ListGroupsPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSystemSCIMv2ListGroupsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /system/pools/{ipID}/scim/v2/Groups] systemSCIMv2ListGroups", response, response.Code())
	}
}

// NewSystemSCIMv2ListGroupsOK creates a SystemSCIMv2ListGroupsOK with default headers values
func NewSystemSCIMv2ListGroupsOK() *SystemSCIMv2ListGroupsOK {
	return &SystemSCIMv2ListGroupsOK{}
}

/*
SystemSCIMv2ListGroupsOK describes a response with status code 200, with default header values.

SCIMv2 Groups
*/
type SystemSCIMv2ListGroupsOK struct {
	Payload *models.ListGroupsResponse
}

// IsSuccess returns true when this system s c i mv2 list groups o k response has a 2xx status code
func (o *SystemSCIMv2ListGroupsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system s c i mv2 list groups o k response has a 3xx status code
func (o *SystemSCIMv2ListGroupsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups o k response has a 4xx status code
func (o *SystemSCIMv2ListGroupsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system s c i mv2 list groups o k response has a 5xx status code
func (o *SystemSCIMv2ListGroupsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups o k response a status code equal to that given
func (o *SystemSCIMv2ListGroupsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the system s c i mv2 list groups o k response
func (o *SystemSCIMv2ListGroupsOK) Code() int {
	return 200
}

func (o *SystemSCIMv2ListGroupsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsOK %s", 200, payload)
}

func (o *SystemSCIMv2ListGroupsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsOK %s", 200, payload)
}

func (o *SystemSCIMv2ListGroupsOK) GetPayload() *models.ListGroupsResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListGroupsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsBadRequest creates a SystemSCIMv2ListGroupsBadRequest with default headers values
func NewSystemSCIMv2ListGroupsBadRequest() *SystemSCIMv2ListGroupsBadRequest {
	return &SystemSCIMv2ListGroupsBadRequest{}
}

/*
SystemSCIMv2ListGroupsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SystemSCIMv2ListGroupsBadRequest struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups bad request response has a 2xx status code
func (o *SystemSCIMv2ListGroupsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups bad request response has a 3xx status code
func (o *SystemSCIMv2ListGroupsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups bad request response has a 4xx status code
func (o *SystemSCIMv2ListGroupsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups bad request response has a 5xx status code
func (o *SystemSCIMv2ListGroupsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups bad request response a status code equal to that given
func (o *SystemSCIMv2ListGroupsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the system s c i mv2 list groups bad request response
func (o *SystemSCIMv2ListGroupsBadRequest) Code() int {
	return 400
}

func (o *SystemSCIMv2ListGroupsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2ListGroupsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2ListGroupsBadRequest) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsUnauthorized creates a SystemSCIMv2ListGroupsUnauthorized with default headers values
func NewSystemSCIMv2ListGroupsUnauthorized() *SystemSCIMv2ListGroupsUnauthorized {
	return &SystemSCIMv2ListGroupsUnauthorized{}
}

/*
SystemSCIMv2ListGroupsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SystemSCIMv2ListGroupsUnauthorized struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups unauthorized response has a 2xx status code
func (o *SystemSCIMv2ListGroupsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups unauthorized response has a 3xx status code
func (o *SystemSCIMv2ListGroupsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups unauthorized response has a 4xx status code
func (o *SystemSCIMv2ListGroupsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups unauthorized response has a 5xx status code
func (o *SystemSCIMv2ListGroupsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups unauthorized response a status code equal to that given
func (o *SystemSCIMv2ListGroupsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the system s c i mv2 list groups unauthorized response
func (o *SystemSCIMv2ListGroupsUnauthorized) Code() int {
	return 401
}

func (o *SystemSCIMv2ListGroupsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2ListGroupsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2ListGroupsUnauthorized) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsForbidden creates a SystemSCIMv2ListGroupsForbidden with default headers values
func NewSystemSCIMv2ListGroupsForbidden() *SystemSCIMv2ListGroupsForbidden {
	return &SystemSCIMv2ListGroupsForbidden{}
}

/*
SystemSCIMv2ListGroupsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SystemSCIMv2ListGroupsForbidden struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups forbidden response has a 2xx status code
func (o *SystemSCIMv2ListGroupsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups forbidden response has a 3xx status code
func (o *SystemSCIMv2ListGroupsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups forbidden response has a 4xx status code
func (o *SystemSCIMv2ListGroupsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups forbidden response has a 5xx status code
func (o *SystemSCIMv2ListGroupsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups forbidden response a status code equal to that given
func (o *SystemSCIMv2ListGroupsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the system s c i mv2 list groups forbidden response
func (o *SystemSCIMv2ListGroupsForbidden) Code() int {
	return 403
}

func (o *SystemSCIMv2ListGroupsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsForbidden %s", 403, payload)
}

func (o *SystemSCIMv2ListGroupsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsForbidden %s", 403, payload)
}

func (o *SystemSCIMv2ListGroupsForbidden) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsNotFound creates a SystemSCIMv2ListGroupsNotFound with default headers values
func NewSystemSCIMv2ListGroupsNotFound() *SystemSCIMv2ListGroupsNotFound {
	return &SystemSCIMv2ListGroupsNotFound{}
}

/*
SystemSCIMv2ListGroupsNotFound describes a response with status code 404, with default header values.

Not found
*/
type SystemSCIMv2ListGroupsNotFound struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups not found response has a 2xx status code
func (o *SystemSCIMv2ListGroupsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups not found response has a 3xx status code
func (o *SystemSCIMv2ListGroupsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups not found response has a 4xx status code
func (o *SystemSCIMv2ListGroupsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups not found response has a 5xx status code
func (o *SystemSCIMv2ListGroupsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups not found response a status code equal to that given
func (o *SystemSCIMv2ListGroupsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the system s c i mv2 list groups not found response
func (o *SystemSCIMv2ListGroupsNotFound) Code() int {
	return 404
}

func (o *SystemSCIMv2ListGroupsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsNotFound %s", 404, payload)
}

func (o *SystemSCIMv2ListGroupsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsNotFound %s", 404, payload)
}

func (o *SystemSCIMv2ListGroupsNotFound) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsPreconditionFailed creates a SystemSCIMv2ListGroupsPreconditionFailed with default headers values
func NewSystemSCIMv2ListGroupsPreconditionFailed() *SystemSCIMv2ListGroupsPreconditionFailed {
	return &SystemSCIMv2ListGroupsPreconditionFailed{}
}

/*
SystemSCIMv2ListGroupsPreconditionFailed describes a response with status code 412, with default header values.

Payload too large
*/
type SystemSCIMv2ListGroupsPreconditionFailed struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups precondition failed response has a 2xx status code
func (o *SystemSCIMv2ListGroupsPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups precondition failed response has a 3xx status code
func (o *SystemSCIMv2ListGroupsPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups precondition failed response has a 4xx status code
func (o *SystemSCIMv2ListGroupsPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups precondition failed response has a 5xx status code
func (o *SystemSCIMv2ListGroupsPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups precondition failed response a status code equal to that given
func (o *SystemSCIMv2ListGroupsPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the system s c i mv2 list groups precondition failed response
func (o *SystemSCIMv2ListGroupsPreconditionFailed) Code() int {
	return 412
}

func (o *SystemSCIMv2ListGroupsPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2ListGroupsPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2ListGroupsPreconditionFailed) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2ListGroupsTooManyRequests creates a SystemSCIMv2ListGroupsTooManyRequests with default headers values
func NewSystemSCIMv2ListGroupsTooManyRequests() *SystemSCIMv2ListGroupsTooManyRequests {
	return &SystemSCIMv2ListGroupsTooManyRequests{}
}

/*
SystemSCIMv2ListGroupsTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SystemSCIMv2ListGroupsTooManyRequests struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 list groups too many requests response has a 2xx status code
func (o *SystemSCIMv2ListGroupsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 list groups too many requests response has a 3xx status code
func (o *SystemSCIMv2ListGroupsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 list groups too many requests response has a 4xx status code
func (o *SystemSCIMv2ListGroupsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 list groups too many requests response has a 5xx status code
func (o *SystemSCIMv2ListGroupsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 list groups too many requests response a status code equal to that given
func (o *SystemSCIMv2ListGroupsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the system s c i mv2 list groups too many requests response
func (o *SystemSCIMv2ListGroupsTooManyRequests) Code() int {
	return 429
}

func (o *SystemSCIMv2ListGroupsTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2ListGroupsTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups][%d] systemSCIMv2ListGroupsTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2ListGroupsTooManyRequests) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2ListGroupsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
