// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// SystemSCIMv2UpdateUserReader is a Reader for the SystemSCIMv2UpdateUser structure.
type SystemSCIMv2UpdateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemSCIMv2UpdateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemSCIMv2UpdateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSystemSCIMv2UpdateUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSystemSCIMv2UpdateUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSystemSCIMv2UpdateUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSystemSCIMv2UpdateUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSystemSCIMv2UpdateUserConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewSystemSCIMv2UpdateUserPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSystemSCIMv2UpdateUserTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}] systemSCIMv2UpdateUser", response, response.Code())
	}
}

// NewSystemSCIMv2UpdateUserOK creates a SystemSCIMv2UpdateUserOK with default headers values
func NewSystemSCIMv2UpdateUserOK() *SystemSCIMv2UpdateUserOK {
	return &SystemSCIMv2UpdateUserOK{}
}

/*
SystemSCIMv2UpdateUserOK describes a response with status code 200, with default header values.

SCIMv2 User
*/
type SystemSCIMv2UpdateUserOK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.UserGetResponse
}

// IsSuccess returns true when this system s c i mv2 update user o k response has a 2xx status code
func (o *SystemSCIMv2UpdateUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system s c i mv2 update user o k response has a 3xx status code
func (o *SystemSCIMv2UpdateUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user o k response has a 4xx status code
func (o *SystemSCIMv2UpdateUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system s c i mv2 update user o k response has a 5xx status code
func (o *SystemSCIMv2UpdateUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user o k response a status code equal to that given
func (o *SystemSCIMv2UpdateUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the system s c i mv2 update user o k response
func (o *SystemSCIMv2UpdateUserOK) Code() int {
	return 200
}

func (o *SystemSCIMv2UpdateUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserOK %s", 200, payload)
}

func (o *SystemSCIMv2UpdateUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserOK %s", 200, payload)
}

func (o *SystemSCIMv2UpdateUserOK) GetPayload() *models.UserGetResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.UserGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserBadRequest creates a SystemSCIMv2UpdateUserBadRequest with default headers values
func NewSystemSCIMv2UpdateUserBadRequest() *SystemSCIMv2UpdateUserBadRequest {
	return &SystemSCIMv2UpdateUserBadRequest{}
}

/*
SystemSCIMv2UpdateUserBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SystemSCIMv2UpdateUserBadRequest struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user bad request response has a 2xx status code
func (o *SystemSCIMv2UpdateUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user bad request response has a 3xx status code
func (o *SystemSCIMv2UpdateUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user bad request response has a 4xx status code
func (o *SystemSCIMv2UpdateUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user bad request response has a 5xx status code
func (o *SystemSCIMv2UpdateUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user bad request response a status code equal to that given
func (o *SystemSCIMv2UpdateUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the system s c i mv2 update user bad request response
func (o *SystemSCIMv2UpdateUserBadRequest) Code() int {
	return 400
}

func (o *SystemSCIMv2UpdateUserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2UpdateUserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2UpdateUserBadRequest) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserUnauthorized creates a SystemSCIMv2UpdateUserUnauthorized with default headers values
func NewSystemSCIMv2UpdateUserUnauthorized() *SystemSCIMv2UpdateUserUnauthorized {
	return &SystemSCIMv2UpdateUserUnauthorized{}
}

/*
SystemSCIMv2UpdateUserUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SystemSCIMv2UpdateUserUnauthorized struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user unauthorized response has a 2xx status code
func (o *SystemSCIMv2UpdateUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user unauthorized response has a 3xx status code
func (o *SystemSCIMv2UpdateUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user unauthorized response has a 4xx status code
func (o *SystemSCIMv2UpdateUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user unauthorized response has a 5xx status code
func (o *SystemSCIMv2UpdateUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user unauthorized response a status code equal to that given
func (o *SystemSCIMv2UpdateUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the system s c i mv2 update user unauthorized response
func (o *SystemSCIMv2UpdateUserUnauthorized) Code() int {
	return 401
}

func (o *SystemSCIMv2UpdateUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2UpdateUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2UpdateUserUnauthorized) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserForbidden creates a SystemSCIMv2UpdateUserForbidden with default headers values
func NewSystemSCIMv2UpdateUserForbidden() *SystemSCIMv2UpdateUserForbidden {
	return &SystemSCIMv2UpdateUserForbidden{}
}

/*
SystemSCIMv2UpdateUserForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SystemSCIMv2UpdateUserForbidden struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user forbidden response has a 2xx status code
func (o *SystemSCIMv2UpdateUserForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user forbidden response has a 3xx status code
func (o *SystemSCIMv2UpdateUserForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user forbidden response has a 4xx status code
func (o *SystemSCIMv2UpdateUserForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user forbidden response has a 5xx status code
func (o *SystemSCIMv2UpdateUserForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user forbidden response a status code equal to that given
func (o *SystemSCIMv2UpdateUserForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the system s c i mv2 update user forbidden response
func (o *SystemSCIMv2UpdateUserForbidden) Code() int {
	return 403
}

func (o *SystemSCIMv2UpdateUserForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserForbidden %s", 403, payload)
}

func (o *SystemSCIMv2UpdateUserForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserForbidden %s", 403, payload)
}

func (o *SystemSCIMv2UpdateUserForbidden) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserNotFound creates a SystemSCIMv2UpdateUserNotFound with default headers values
func NewSystemSCIMv2UpdateUserNotFound() *SystemSCIMv2UpdateUserNotFound {
	return &SystemSCIMv2UpdateUserNotFound{}
}

/*
SystemSCIMv2UpdateUserNotFound describes a response with status code 404, with default header values.

Not found
*/
type SystemSCIMv2UpdateUserNotFound struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user not found response has a 2xx status code
func (o *SystemSCIMv2UpdateUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user not found response has a 3xx status code
func (o *SystemSCIMv2UpdateUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user not found response has a 4xx status code
func (o *SystemSCIMv2UpdateUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user not found response has a 5xx status code
func (o *SystemSCIMv2UpdateUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user not found response a status code equal to that given
func (o *SystemSCIMv2UpdateUserNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the system s c i mv2 update user not found response
func (o *SystemSCIMv2UpdateUserNotFound) Code() int {
	return 404
}

func (o *SystemSCIMv2UpdateUserNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserNotFound %s", 404, payload)
}

func (o *SystemSCIMv2UpdateUserNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserNotFound %s", 404, payload)
}

func (o *SystemSCIMv2UpdateUserNotFound) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserConflict creates a SystemSCIMv2UpdateUserConflict with default headers values
func NewSystemSCIMv2UpdateUserConflict() *SystemSCIMv2UpdateUserConflict {
	return &SystemSCIMv2UpdateUserConflict{}
}

/*
SystemSCIMv2UpdateUserConflict describes a response with status code 409, with default header values.

Conflict
*/
type SystemSCIMv2UpdateUserConflict struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user conflict response has a 2xx status code
func (o *SystemSCIMv2UpdateUserConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user conflict response has a 3xx status code
func (o *SystemSCIMv2UpdateUserConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user conflict response has a 4xx status code
func (o *SystemSCIMv2UpdateUserConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user conflict response has a 5xx status code
func (o *SystemSCIMv2UpdateUserConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user conflict response a status code equal to that given
func (o *SystemSCIMv2UpdateUserConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the system s c i mv2 update user conflict response
func (o *SystemSCIMv2UpdateUserConflict) Code() int {
	return 409
}

func (o *SystemSCIMv2UpdateUserConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserConflict %s", 409, payload)
}

func (o *SystemSCIMv2UpdateUserConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserConflict %s", 409, payload)
}

func (o *SystemSCIMv2UpdateUserConflict) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserPreconditionFailed creates a SystemSCIMv2UpdateUserPreconditionFailed with default headers values
func NewSystemSCIMv2UpdateUserPreconditionFailed() *SystemSCIMv2UpdateUserPreconditionFailed {
	return &SystemSCIMv2UpdateUserPreconditionFailed{}
}

/*
SystemSCIMv2UpdateUserPreconditionFailed describes a response with status code 412, with default header values.

Payload too large
*/
type SystemSCIMv2UpdateUserPreconditionFailed struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user precondition failed response has a 2xx status code
func (o *SystemSCIMv2UpdateUserPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user precondition failed response has a 3xx status code
func (o *SystemSCIMv2UpdateUserPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user precondition failed response has a 4xx status code
func (o *SystemSCIMv2UpdateUserPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user precondition failed response has a 5xx status code
func (o *SystemSCIMv2UpdateUserPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user precondition failed response a status code equal to that given
func (o *SystemSCIMv2UpdateUserPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the system s c i mv2 update user precondition failed response
func (o *SystemSCIMv2UpdateUserPreconditionFailed) Code() int {
	return 412
}

func (o *SystemSCIMv2UpdateUserPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2UpdateUserPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2UpdateUserPreconditionFailed) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateUserTooManyRequests creates a SystemSCIMv2UpdateUserTooManyRequests with default headers values
func NewSystemSCIMv2UpdateUserTooManyRequests() *SystemSCIMv2UpdateUserTooManyRequests {
	return &SystemSCIMv2UpdateUserTooManyRequests{}
}

/*
SystemSCIMv2UpdateUserTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SystemSCIMv2UpdateUserTooManyRequests struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update user too many requests response has a 2xx status code
func (o *SystemSCIMv2UpdateUserTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update user too many requests response has a 3xx status code
func (o *SystemSCIMv2UpdateUserTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update user too many requests response has a 4xx status code
func (o *SystemSCIMv2UpdateUserTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update user too many requests response has a 5xx status code
func (o *SystemSCIMv2UpdateUserTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update user too many requests response a status code equal to that given
func (o *SystemSCIMv2UpdateUserTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the system s c i mv2 update user too many requests response
func (o *SystemSCIMv2UpdateUserTooManyRequests) Code() int {
	return 429
}

func (o *SystemSCIMv2UpdateUserTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2UpdateUserTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Users/{userID}][%d] systemSCIMv2UpdateUserTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2UpdateUserTooManyRequests) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateUserTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
