// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// SystemSCIMv2GetGroupReader is a Reader for the SystemSCIMv2GetGroup structure.
type SystemSCIMv2GetGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemSCIMv2GetGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemSCIMv2GetGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSystemSCIMv2GetGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSystemSCIMv2GetGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSystemSCIMv2GetGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewSystemSCIMv2GetGroupPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSystemSCIMv2GetGroupUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSystemSCIMv2GetGroupTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}] systemSCIMv2GetGroup", response, response.Code())
	}
}

// NewSystemSCIMv2GetGroupOK creates a SystemSCIMv2GetGroupOK with default headers values
func NewSystemSCIMv2GetGroupOK() *SystemSCIMv2GetGroupOK {
	return &SystemSCIMv2GetGroupOK{}
}

/*
SystemSCIMv2GetGroupOK describes a response with status code 200, with default header values.

SCIMv2 Group
*/
type SystemSCIMv2GetGroupOK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.GroupGetResponse
}

// IsSuccess returns true when this system s c i mv2 get group o k response has a 2xx status code
func (o *SystemSCIMv2GetGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system s c i mv2 get group o k response has a 3xx status code
func (o *SystemSCIMv2GetGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group o k response has a 4xx status code
func (o *SystemSCIMv2GetGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system s c i mv2 get group o k response has a 5xx status code
func (o *SystemSCIMv2GetGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group o k response a status code equal to that given
func (o *SystemSCIMv2GetGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the system s c i mv2 get group o k response
func (o *SystemSCIMv2GetGroupOK) Code() int {
	return 200
}

func (o *SystemSCIMv2GetGroupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupOK %s", 200, payload)
}

func (o *SystemSCIMv2GetGroupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupOK %s", 200, payload)
}

func (o *SystemSCIMv2GetGroupOK) GetPayload() *models.GroupGetResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.GroupGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupUnauthorized creates a SystemSCIMv2GetGroupUnauthorized with default headers values
func NewSystemSCIMv2GetGroupUnauthorized() *SystemSCIMv2GetGroupUnauthorized {
	return &SystemSCIMv2GetGroupUnauthorized{}
}

/*
SystemSCIMv2GetGroupUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SystemSCIMv2GetGroupUnauthorized struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group unauthorized response has a 2xx status code
func (o *SystemSCIMv2GetGroupUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group unauthorized response has a 3xx status code
func (o *SystemSCIMv2GetGroupUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group unauthorized response has a 4xx status code
func (o *SystemSCIMv2GetGroupUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group unauthorized response has a 5xx status code
func (o *SystemSCIMv2GetGroupUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group unauthorized response a status code equal to that given
func (o *SystemSCIMv2GetGroupUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the system s c i mv2 get group unauthorized response
func (o *SystemSCIMv2GetGroupUnauthorized) Code() int {
	return 401
}

func (o *SystemSCIMv2GetGroupUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2GetGroupUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2GetGroupUnauthorized) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupForbidden creates a SystemSCIMv2GetGroupForbidden with default headers values
func NewSystemSCIMv2GetGroupForbidden() *SystemSCIMv2GetGroupForbidden {
	return &SystemSCIMv2GetGroupForbidden{}
}

/*
SystemSCIMv2GetGroupForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SystemSCIMv2GetGroupForbidden struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group forbidden response has a 2xx status code
func (o *SystemSCIMv2GetGroupForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group forbidden response has a 3xx status code
func (o *SystemSCIMv2GetGroupForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group forbidden response has a 4xx status code
func (o *SystemSCIMv2GetGroupForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group forbidden response has a 5xx status code
func (o *SystemSCIMv2GetGroupForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group forbidden response a status code equal to that given
func (o *SystemSCIMv2GetGroupForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the system s c i mv2 get group forbidden response
func (o *SystemSCIMv2GetGroupForbidden) Code() int {
	return 403
}

func (o *SystemSCIMv2GetGroupForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupForbidden %s", 403, payload)
}

func (o *SystemSCIMv2GetGroupForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupForbidden %s", 403, payload)
}

func (o *SystemSCIMv2GetGroupForbidden) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupNotFound creates a SystemSCIMv2GetGroupNotFound with default headers values
func NewSystemSCIMv2GetGroupNotFound() *SystemSCIMv2GetGroupNotFound {
	return &SystemSCIMv2GetGroupNotFound{}
}

/*
SystemSCIMv2GetGroupNotFound describes a response with status code 404, with default header values.

Not found
*/
type SystemSCIMv2GetGroupNotFound struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group not found response has a 2xx status code
func (o *SystemSCIMv2GetGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group not found response has a 3xx status code
func (o *SystemSCIMv2GetGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group not found response has a 4xx status code
func (o *SystemSCIMv2GetGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group not found response has a 5xx status code
func (o *SystemSCIMv2GetGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group not found response a status code equal to that given
func (o *SystemSCIMv2GetGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the system s c i mv2 get group not found response
func (o *SystemSCIMv2GetGroupNotFound) Code() int {
	return 404
}

func (o *SystemSCIMv2GetGroupNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupNotFound %s", 404, payload)
}

func (o *SystemSCIMv2GetGroupNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupNotFound %s", 404, payload)
}

func (o *SystemSCIMv2GetGroupNotFound) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupPreconditionFailed creates a SystemSCIMv2GetGroupPreconditionFailed with default headers values
func NewSystemSCIMv2GetGroupPreconditionFailed() *SystemSCIMv2GetGroupPreconditionFailed {
	return &SystemSCIMv2GetGroupPreconditionFailed{}
}

/*
SystemSCIMv2GetGroupPreconditionFailed describes a response with status code 412, with default header values.

Payload too large
*/
type SystemSCIMv2GetGroupPreconditionFailed struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group precondition failed response has a 2xx status code
func (o *SystemSCIMv2GetGroupPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group precondition failed response has a 3xx status code
func (o *SystemSCIMv2GetGroupPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group precondition failed response has a 4xx status code
func (o *SystemSCIMv2GetGroupPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group precondition failed response has a 5xx status code
func (o *SystemSCIMv2GetGroupPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group precondition failed response a status code equal to that given
func (o *SystemSCIMv2GetGroupPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the system s c i mv2 get group precondition failed response
func (o *SystemSCIMv2GetGroupPreconditionFailed) Code() int {
	return 412
}

func (o *SystemSCIMv2GetGroupPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2GetGroupPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2GetGroupPreconditionFailed) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupUnprocessableEntity creates a SystemSCIMv2GetGroupUnprocessableEntity with default headers values
func NewSystemSCIMv2GetGroupUnprocessableEntity() *SystemSCIMv2GetGroupUnprocessableEntity {
	return &SystemSCIMv2GetGroupUnprocessableEntity{}
}

/*
SystemSCIMv2GetGroupUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type SystemSCIMv2GetGroupUnprocessableEntity struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group unprocessable entity response has a 2xx status code
func (o *SystemSCIMv2GetGroupUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group unprocessable entity response has a 3xx status code
func (o *SystemSCIMv2GetGroupUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group unprocessable entity response has a 4xx status code
func (o *SystemSCIMv2GetGroupUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group unprocessable entity response has a 5xx status code
func (o *SystemSCIMv2GetGroupUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group unprocessable entity response a status code equal to that given
func (o *SystemSCIMv2GetGroupUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the system s c i mv2 get group unprocessable entity response
func (o *SystemSCIMv2GetGroupUnprocessableEntity) Code() int {
	return 422
}

func (o *SystemSCIMv2GetGroupUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupUnprocessableEntity %s", 422, payload)
}

func (o *SystemSCIMv2GetGroupUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupUnprocessableEntity %s", 422, payload)
}

func (o *SystemSCIMv2GetGroupUnprocessableEntity) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2GetGroupTooManyRequests creates a SystemSCIMv2GetGroupTooManyRequests with default headers values
func NewSystemSCIMv2GetGroupTooManyRequests() *SystemSCIMv2GetGroupTooManyRequests {
	return &SystemSCIMv2GetGroupTooManyRequests{}
}

/*
SystemSCIMv2GetGroupTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SystemSCIMv2GetGroupTooManyRequests struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 get group too many requests response has a 2xx status code
func (o *SystemSCIMv2GetGroupTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 get group too many requests response has a 3xx status code
func (o *SystemSCIMv2GetGroupTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 get group too many requests response has a 4xx status code
func (o *SystemSCIMv2GetGroupTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 get group too many requests response has a 5xx status code
func (o *SystemSCIMv2GetGroupTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 get group too many requests response a status code equal to that given
func (o *SystemSCIMv2GetGroupTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the system s c i mv2 get group too many requests response
func (o *SystemSCIMv2GetGroupTooManyRequests) Code() int {
	return 429
}

func (o *SystemSCIMv2GetGroupTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2GetGroupTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2GetGroupTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2GetGroupTooManyRequests) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2GetGroupTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
