// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// SystemSCIMv2UpdateGroupReader is a Reader for the SystemSCIMv2UpdateGroup structure.
type SystemSCIMv2UpdateGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemSCIMv2UpdateGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemSCIMv2UpdateGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSystemSCIMv2UpdateGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSystemSCIMv2UpdateGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSystemSCIMv2UpdateGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSystemSCIMv2UpdateGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSystemSCIMv2UpdateGroupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewSystemSCIMv2UpdateGroupPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSystemSCIMv2UpdateGroupTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}] systemSCIMv2UpdateGroup", response, response.Code())
	}
}

// NewSystemSCIMv2UpdateGroupOK creates a SystemSCIMv2UpdateGroupOK with default headers values
func NewSystemSCIMv2UpdateGroupOK() *SystemSCIMv2UpdateGroupOK {
	return &SystemSCIMv2UpdateGroupOK{}
}

/*
SystemSCIMv2UpdateGroupOK describes a response with status code 200, with default header values.

SCIMv2 Group
*/
type SystemSCIMv2UpdateGroupOK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.GroupGetResponse
}

// IsSuccess returns true when this system s c i mv2 update group o k response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system s c i mv2 update group o k response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group o k response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system s c i mv2 update group o k response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group o k response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the system s c i mv2 update group o k response
func (o *SystemSCIMv2UpdateGroupOK) Code() int {
	return 200
}

func (o *SystemSCIMv2UpdateGroupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupOK %s", 200, payload)
}

func (o *SystemSCIMv2UpdateGroupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupOK %s", 200, payload)
}

func (o *SystemSCIMv2UpdateGroupOK) GetPayload() *models.GroupGetResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.GroupGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupBadRequest creates a SystemSCIMv2UpdateGroupBadRequest with default headers values
func NewSystemSCIMv2UpdateGroupBadRequest() *SystemSCIMv2UpdateGroupBadRequest {
	return &SystemSCIMv2UpdateGroupBadRequest{}
}

/*
SystemSCIMv2UpdateGroupBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SystemSCIMv2UpdateGroupBadRequest struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group bad request response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group bad request response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group bad request response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group bad request response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group bad request response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the system s c i mv2 update group bad request response
func (o *SystemSCIMv2UpdateGroupBadRequest) Code() int {
	return 400
}

func (o *SystemSCIMv2UpdateGroupBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2UpdateGroupBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupBadRequest %s", 400, payload)
}

func (o *SystemSCIMv2UpdateGroupBadRequest) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupUnauthorized creates a SystemSCIMv2UpdateGroupUnauthorized with default headers values
func NewSystemSCIMv2UpdateGroupUnauthorized() *SystemSCIMv2UpdateGroupUnauthorized {
	return &SystemSCIMv2UpdateGroupUnauthorized{}
}

/*
SystemSCIMv2UpdateGroupUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SystemSCIMv2UpdateGroupUnauthorized struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group unauthorized response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group unauthorized response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group unauthorized response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group unauthorized response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group unauthorized response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the system s c i mv2 update group unauthorized response
func (o *SystemSCIMv2UpdateGroupUnauthorized) Code() int {
	return 401
}

func (o *SystemSCIMv2UpdateGroupUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2UpdateGroupUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupUnauthorized %s", 401, payload)
}

func (o *SystemSCIMv2UpdateGroupUnauthorized) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupForbidden creates a SystemSCIMv2UpdateGroupForbidden with default headers values
func NewSystemSCIMv2UpdateGroupForbidden() *SystemSCIMv2UpdateGroupForbidden {
	return &SystemSCIMv2UpdateGroupForbidden{}
}

/*
SystemSCIMv2UpdateGroupForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SystemSCIMv2UpdateGroupForbidden struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group forbidden response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group forbidden response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group forbidden response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group forbidden response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group forbidden response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the system s c i mv2 update group forbidden response
func (o *SystemSCIMv2UpdateGroupForbidden) Code() int {
	return 403
}

func (o *SystemSCIMv2UpdateGroupForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupForbidden %s", 403, payload)
}

func (o *SystemSCIMv2UpdateGroupForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupForbidden %s", 403, payload)
}

func (o *SystemSCIMv2UpdateGroupForbidden) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupNotFound creates a SystemSCIMv2UpdateGroupNotFound with default headers values
func NewSystemSCIMv2UpdateGroupNotFound() *SystemSCIMv2UpdateGroupNotFound {
	return &SystemSCIMv2UpdateGroupNotFound{}
}

/*
SystemSCIMv2UpdateGroupNotFound describes a response with status code 404, with default header values.

Not found
*/
type SystemSCIMv2UpdateGroupNotFound struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group not found response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group not found response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group not found response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group not found response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group not found response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the system s c i mv2 update group not found response
func (o *SystemSCIMv2UpdateGroupNotFound) Code() int {
	return 404
}

func (o *SystemSCIMv2UpdateGroupNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupNotFound %s", 404, payload)
}

func (o *SystemSCIMv2UpdateGroupNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupNotFound %s", 404, payload)
}

func (o *SystemSCIMv2UpdateGroupNotFound) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupConflict creates a SystemSCIMv2UpdateGroupConflict with default headers values
func NewSystemSCIMv2UpdateGroupConflict() *SystemSCIMv2UpdateGroupConflict {
	return &SystemSCIMv2UpdateGroupConflict{}
}

/*
SystemSCIMv2UpdateGroupConflict describes a response with status code 409, with default header values.

Conflict
*/
type SystemSCIMv2UpdateGroupConflict struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group conflict response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group conflict response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group conflict response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group conflict response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group conflict response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the system s c i mv2 update group conflict response
func (o *SystemSCIMv2UpdateGroupConflict) Code() int {
	return 409
}

func (o *SystemSCIMv2UpdateGroupConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupConflict %s", 409, payload)
}

func (o *SystemSCIMv2UpdateGroupConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupConflict %s", 409, payload)
}

func (o *SystemSCIMv2UpdateGroupConflict) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupPreconditionFailed creates a SystemSCIMv2UpdateGroupPreconditionFailed with default headers values
func NewSystemSCIMv2UpdateGroupPreconditionFailed() *SystemSCIMv2UpdateGroupPreconditionFailed {
	return &SystemSCIMv2UpdateGroupPreconditionFailed{}
}

/*
SystemSCIMv2UpdateGroupPreconditionFailed describes a response with status code 412, with default header values.

Payload too large
*/
type SystemSCIMv2UpdateGroupPreconditionFailed struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group precondition failed response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group precondition failed response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group precondition failed response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group precondition failed response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group precondition failed response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the system s c i mv2 update group precondition failed response
func (o *SystemSCIMv2UpdateGroupPreconditionFailed) Code() int {
	return 412
}

func (o *SystemSCIMv2UpdateGroupPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2UpdateGroupPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupPreconditionFailed %s", 412, payload)
}

func (o *SystemSCIMv2UpdateGroupPreconditionFailed) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemSCIMv2UpdateGroupTooManyRequests creates a SystemSCIMv2UpdateGroupTooManyRequests with default headers values
func NewSystemSCIMv2UpdateGroupTooManyRequests() *SystemSCIMv2UpdateGroupTooManyRequests {
	return &SystemSCIMv2UpdateGroupTooManyRequests{}
}

/*
SystemSCIMv2UpdateGroupTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SystemSCIMv2UpdateGroupTooManyRequests struct {
	Payload *models.SCIMv2ErrorResponse
}

// IsSuccess returns true when this system s c i mv2 update group too many requests response has a 2xx status code
func (o *SystemSCIMv2UpdateGroupTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this system s c i mv2 update group too many requests response has a 3xx status code
func (o *SystemSCIMv2UpdateGroupTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system s c i mv2 update group too many requests response has a 4xx status code
func (o *SystemSCIMv2UpdateGroupTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this system s c i mv2 update group too many requests response has a 5xx status code
func (o *SystemSCIMv2UpdateGroupTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this system s c i mv2 update group too many requests response a status code equal to that given
func (o *SystemSCIMv2UpdateGroupTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the system s c i mv2 update group too many requests response
func (o *SystemSCIMv2UpdateGroupTooManyRequests) Code() int {
	return 429
}

func (o *SystemSCIMv2UpdateGroupTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2UpdateGroupTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /system/pools/{ipID}/scim/v2/Groups/{groupID}][%d] systemSCIMv2UpdateGroupTooManyRequests %s", 429, payload)
}

func (o *SystemSCIMv2UpdateGroupTooManyRequests) GetPayload() *models.SCIMv2ErrorResponse {
	return o.Payload
}

func (o *SystemSCIMv2UpdateGroupTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SCIMv2ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
