// Code generated by go-swagger; DO NOT EDIT.

package version2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new version2 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new version2 API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new version2 API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for version2 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationScimJSON sets the Accept header to "application/scim+json".
func WithAcceptApplicationScimJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/scim+json"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	SystemSCIMv2CreateUser(params *SystemSCIMv2CreateUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2CreateUserCreated, error)

	SystemSCIMv2DeleteUser(params *SystemSCIMv2DeleteUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2DeleteUserNoContent, error)

	SystemSCIMv2GetResourceType(params *SystemSCIMv2GetResourceTypeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetResourceTypeOK, error)

	SystemSCIMv2GetResourceTypes(params *SystemSCIMv2GetResourceTypesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetResourceTypesOK, error)

	SystemSCIMv2GetServiceProviderConfig(params *SystemSCIMv2GetServiceProviderConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetServiceProviderConfigOK, error)

	SystemSCIMv2GetSystemGetSCIMv2Schema(params *SystemSCIMv2GetSystemGetSCIMv2SchemaParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetSystemGetSCIMv2SchemaOK, error)

	SystemSCIMv2GetSystemGetSCIMv2Schemas(params *SystemSCIMv2GetSystemGetSCIMv2SchemasParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetSystemGetSCIMv2SchemasOK, error)

	SystemSCIMv2GetUser(params *SystemSCIMv2GetUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetUserOK, error)

	SystemSCIMv2ListUsers(params *SystemSCIMv2ListUsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2ListUsersOK, error)

	SystemSCIMv2PatchUser(params *SystemSCIMv2PatchUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2PatchUserOK, error)

	SystemSCIMv2UpdateUser(params *SystemSCIMv2UpdateUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2UpdateUserOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
SystemSCIMv2CreateUser creates s c i m user

Creates a new user in SCIM format in the specified identity pool.
*/
func (a *Client) SystemSCIMv2CreateUser(params *SystemSCIMv2CreateUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2CreateUserCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2CreateUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2CreateUser",
		Method:             "POST",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2CreateUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2CreateUserCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2CreateUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2DeleteUser deletes s c i m user

Deletes a user using SCIM DELETE operations in the specified identity pool.
*/
func (a *Client) SystemSCIMv2DeleteUser(params *SystemSCIMv2DeleteUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2DeleteUserNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2DeleteUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2DeleteUser",
		Method:             "DELETE",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users/{userID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2DeleteUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2DeleteUserNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2DeleteUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetResourceType gets s c i m resource type

Returns requested SCIM Resource Type for the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetResourceType(params *SystemSCIMv2GetResourceTypeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetResourceTypeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetResourceTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetResourceType",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/ResourceTypes/{resourceID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetResourceTypeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetResourceTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetResourceType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetResourceTypes lists s c i m resource types

Returns the supported SCIM Resource Types for the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetResourceTypes(params *SystemSCIMv2GetResourceTypesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetResourceTypesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetResourceTypesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetResourceTypes",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/ResourceTypes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetResourceTypesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetResourceTypesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetResourceTypes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetServiceProviderConfig gets s c i m service provider configuration

Returns the SCIM Service Provider Configuration for the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetServiceProviderConfig(params *SystemSCIMv2GetServiceProviderConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetServiceProviderConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetServiceProviderConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetServiceProviderConfig",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/ServiceProviderConfig",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetServiceProviderConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetServiceProviderConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetServiceProviderConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetSystemGetSCIMv2Schema gets s c i m schemas

Returns requested SCIM Schema for the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetSystemGetSCIMv2Schema(params *SystemSCIMv2GetSystemGetSCIMv2SchemaParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetSystemGetSCIMv2SchemaOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetSystemGetSCIMv2SchemaParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetSystemGetSCIMv2Schema",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Schemas/{schemaID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetSystemGetSCIMv2SchemaReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetSystemGetSCIMv2SchemaOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetSystemGetSCIMv2Schema: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetSystemGetSCIMv2Schemas lists s c i m schemas

Returns the supported SCIM Schemas for the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetSystemGetSCIMv2Schemas(params *SystemSCIMv2GetSystemGetSCIMv2SchemasParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetSystemGetSCIMv2SchemasOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetSystemGetSCIMv2SchemasParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetSystemGetSCIMv2Schemas",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Schemas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetSystemGetSCIMv2SchemasReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetSystemGetSCIMv2SchemasOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetSystemGetSCIMv2Schemas: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2GetUser gets s c i m user

Returns a specific user in SCIM format from the specified identity pool.
*/
func (a *Client) SystemSCIMv2GetUser(params *SystemSCIMv2GetUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2GetUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2GetUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2GetUser",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users/{userID}",
		ProducesMediaTypes: []string{"application/scim+json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2GetUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2GetUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2GetUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	SystemSCIMv2ListUsers lists s c i m users

	Returns a list of users in SCIM format from the specified identity pool.

The only supported filter is `<fieldName> eq <value>` which returns a single user or empty set.
Allowed field names (case-insensitive) are `id`, `externalId`, `userName`, `emails.value`, and `phoneNumbers.value`.
For emails and phone number subfilter [.*] is allowed but ignored.

Only verified emails and phone numbers are searchable.
*/
func (a *Client) SystemSCIMv2ListUsers(params *SystemSCIMv2ListUsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2ListUsersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2ListUsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2ListUsers",
		Method:             "GET",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2ListUsersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2ListUsersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2ListUsers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	SystemSCIMv2PatchUser patches s c i m user

	Updates a user using SCIM PATCH operations in the specified identity pool.

NOTE: this is very basic PATCH implementation that does not allow filtering in path and strictly follows RFC 6902 with some workarounds.
*/
func (a *Client) SystemSCIMv2PatchUser(params *SystemSCIMv2PatchUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2PatchUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2PatchUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2PatchUser",
		Method:             "PATCH",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users/{userID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2PatchUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2PatchUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2PatchUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SystemSCIMv2UpdateUser updates s c i m user

Updates a user using SCIM format in the specified identity pool (full replacement).
*/
func (a *Client) SystemSCIMv2UpdateUser(params *SystemSCIMv2UpdateUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SystemSCIMv2UpdateUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSystemSCIMv2UpdateUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "systemSCIMv2UpdateUser",
		Method:             "PUT",
		PathPattern:        "/system/pools/{ipID}/scim/v2/Users/{userID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SystemSCIMv2UpdateUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SystemSCIMv2UpdateUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for systemSCIMv2UpdateUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
