// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricUsage metric usage
//
// swagger:model MetricUsage
type MetricUsage struct {

	// limit
	Limit int64 `json:"limit,omitempty" yaml:"limit,omitempty"`

	// used
	Used int64 `json:"used,omitempty" yaml:"used,omitempty"`
}

// Validate validates this metric usage
func (m *MetricUsage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metric usage based on context it is used
func (m *MetricUsage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricUsage) UnmarshalBinary(b []byte) error {
	var res MetricUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
