// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CredentialCreation credential creation
//
// swagger:model CredentialCreation
type CredentialCreation struct {

	// mediation
	Mediation CredentialMediationRequirement `json:"mediation,omitempty" yaml:"mediation,omitempty"`

	// public key
	PublicKey *PublicKeyCredentialCreationOptions `json:"publicKey,omitempty" yaml:"publicKey,omitempty"`
}

// Validate validates this credential creation
func (m *CredentialCreation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialCreation) validateMediation(formats strfmt.Registry) error {
	if swag.IsZero(m.Mediation) { // not required
		return nil
	}

	if err := m.Mediation.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mediation")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("mediation")
		}
		return err
	}

	return nil
}

func (m *CredentialCreation) validatePublicKey(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicKey) { // not required
		return nil
	}

	if m.PublicKey != nil {
		if err := m.PublicKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("publicKey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("publicKey")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this credential creation based on the context it is used
func (m *CredentialCreation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMediation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePublicKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialCreation) contextValidateMediation(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Mediation) { // not required
		return nil
	}

	if err := m.Mediation.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mediation")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("mediation")
		}
		return err
	}

	return nil
}

func (m *CredentialCreation) contextValidatePublicKey(ctx context.Context, formats strfmt.Registry) error {

	if m.PublicKey != nil {

		if swag.IsZero(m.PublicKey) { // not required
			return nil
		}

		if err := m.PublicKey.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("publicKey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("publicKey")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CredentialCreation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialCreation) UnmarshalBinary(b []byte) error {
	var res CredentialCreation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
