// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PRFInputs PRFInputs represents the AuthenticationExtensionsPRFInputsJSON IDL.
//
// Every member is optional. A zero value is the bare availability probe, i.e. the "prf":{} input a Relying Party
// sends at registration to learn whether the pseudo-random function is available for the credential; the client
// answers with the 'enabled' output. This is why [AuthenticationExtensions.PRF] is a pointer while its
// [LargeBlobInputs] and [HMACGetSecretInputs] siblings are not.
//
// EvalByCredential is only valid during authentication; the client throws a NotSupportedError when it is present
// during registration. Its keys are base64url encoded credential IDs which MUST each match an entry of the
// allowed credentials.
//
// Specification: §10.1.4. Pseudo-random function extension (https://www.w3.org/TR/webauthn-3/#prf-extension)
//
// swagger:model PRFInputs
type PRFInputs struct {

	// eval
	Eval *PRFValues `json:"eval,omitempty" yaml:"eval,omitempty"`

	// eval by credential
	EvalByCredential map[string]PRFValues `json:"evalByCredential,omitempty" yaml:"evalByCredential,omitempty"`
}

// Validate validates this p r f inputs
func (m *PRFInputs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvalByCredential(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PRFInputs) validateEval(formats strfmt.Registry) error {
	if swag.IsZero(m.Eval) { // not required
		return nil
	}

	if m.Eval != nil {
		if err := m.Eval.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("eval")
			}
			return err
		}
	}

	return nil
}

func (m *PRFInputs) validateEvalByCredential(formats strfmt.Registry) error {
	if swag.IsZero(m.EvalByCredential) { // not required
		return nil
	}

	for k := range m.EvalByCredential {

		if err := validate.Required("evalByCredential"+"."+k, "body", m.EvalByCredential[k]); err != nil {
			return err
		}
		if val, ok := m.EvalByCredential[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("evalByCredential" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("evalByCredential" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this p r f inputs based on the context it is used
func (m *PRFInputs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEval(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEvalByCredential(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PRFInputs) contextValidateEval(ctx context.Context, formats strfmt.Registry) error {

	if m.Eval != nil {

		if swag.IsZero(m.Eval) { // not required
			return nil
		}

		if err := m.Eval.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eval")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("eval")
			}
			return err
		}
	}

	return nil
}

func (m *PRFInputs) contextValidateEvalByCredential(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.EvalByCredential {

		if val, ok := m.EvalByCredential[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PRFInputs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PRFInputs) UnmarshalBinary(b []byte) error {
	var res PRFInputs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
