// Code generated by go-swagger; DO NOT EDIT.

package a_c_rs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// NewUpdateACRParams creates a new UpdateACRParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateACRParams() *UpdateACRParams {
	return &UpdateACRParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateACRParamsWithTimeout creates a new UpdateACRParams object
// with the ability to set a timeout on a request.
func NewUpdateACRParamsWithTimeout(timeout time.Duration) *UpdateACRParams {
	return &UpdateACRParams{
		timeout: timeout,
	}
}

// NewUpdateACRParamsWithContext creates a new UpdateACRParams object
// with the ability to set a context for a request.
func NewUpdateACRParamsWithContext(ctx context.Context) *UpdateACRParams {
	return &UpdateACRParams{
		Context: ctx,
	}
}

// NewUpdateACRParamsWithHTTPClient creates a new UpdateACRParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateACRParamsWithHTTPClient(client *http.Client) *UpdateACRParams {
	return &UpdateACRParams{
		HTTPClient: client,
	}
}

/*
UpdateACRParams contains all the parameters to send to the API endpoint

	for the update a c r operation.

	Typically these are written to a http.Request.
*/
type UpdateACRParams struct {

	// ACR.
	ACR *models.ACR

	/* AcrID.

	   ACR ID
	*/
	AcrID string

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update a c r params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateACRParams) WithDefaults() *UpdateACRParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update a c r params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateACRParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := UpdateACRParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update a c r params
func (o *UpdateACRParams) WithTimeout(timeout time.Duration) *UpdateACRParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update a c r params
func (o *UpdateACRParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update a c r params
func (o *UpdateACRParams) WithContext(ctx context.Context) *UpdateACRParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update a c r params
func (o *UpdateACRParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update a c r params
func (o *UpdateACRParams) WithHTTPClient(client *http.Client) *UpdateACRParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update a c r params
func (o *UpdateACRParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACR adds the aCR to the update a c r params
func (o *UpdateACRParams) WithACR(aCR *models.ACR) *UpdateACRParams {
	o.SetACR(aCR)
	return o
}

// SetACR adds the aCR to the update a c r params
func (o *UpdateACRParams) SetACR(aCR *models.ACR) {
	o.ACR = aCR
}

// WithAcrID adds the acrID to the update a c r params
func (o *UpdateACRParams) WithAcrID(acrID string) *UpdateACRParams {
	o.SetAcrID(acrID)
	return o
}

// SetAcrID adds the acrId to the update a c r params
func (o *UpdateACRParams) SetAcrID(acrID string) {
	o.AcrID = acrID
}

// WithIfMatch adds the ifMatch to the update a c r params
func (o *UpdateACRParams) WithIfMatch(ifMatch *string) *UpdateACRParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the update a c r params
func (o *UpdateACRParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the update a c r params
func (o *UpdateACRParams) WithWid(wid string) *UpdateACRParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the update a c r params
func (o *UpdateACRParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the update a c r params
func (o *UpdateACRParams) WithXCorrelationID(xCorrelationID *string) *UpdateACRParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the update a c r params
func (o *UpdateACRParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the update a c r params
func (o *UpdateACRParams) WithXIdempotencyKey(xIdempotencyKey *string) *UpdateACRParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the update a c r params
func (o *UpdateACRParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateACRParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ACR != nil {
		if err := r.SetBodyParam(o.ACR); err != nil {
			return err
		}
	}

	// path param acrID
	if err := r.SetPathParam("acrID", o.AcrID); err != nil {
		return err
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
