// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// ListIDPsV2Reader is a Reader for the ListIDPsV2 structure.
type ListIDPsV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIDPsV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIDPsV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListIDPsV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListIDPsV2Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListIDPsV2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListIDPsV2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListIDPsV2TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /servers/{wid}/v2/idps] listIDPsV2", response, response.Code())
	}
}

// NewListIDPsV2OK creates a ListIDPsV2OK with default headers values
func NewListIDPsV2OK() *ListIDPsV2OK {
	return &ListIDPsV2OK{}
}

/*
ListIDPsV2OK describes a response with status code 200, with default header values.

IDP
*/
type ListIDPsV2OK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.IDPsResponse
}

// IsSuccess returns true when this list Id ps v2 o k response has a 2xx status code
func (o *ListIDPsV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Id ps v2 o k response has a 3xx status code
func (o *ListIDPsV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 o k response has a 4xx status code
func (o *ListIDPsV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Id ps v2 o k response has a 5xx status code
func (o *ListIDPsV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 o k response a status code equal to that given
func (o *ListIDPsV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Id ps v2 o k response
func (o *ListIDPsV2OK) Code() int {
	return 200
}

func (o *ListIDPsV2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2OK %s", 200, payload)
}

func (o *ListIDPsV2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2OK %s", 200, payload)
}

func (o *ListIDPsV2OK) GetPayload() *models.IDPsResponse {
	return o.Payload
}

func (o *ListIDPsV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.IDPsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIDPsV2BadRequest creates a ListIDPsV2BadRequest with default headers values
func NewListIDPsV2BadRequest() *ListIDPsV2BadRequest {
	return &ListIDPsV2BadRequest{}
}

/*
ListIDPsV2BadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ListIDPsV2BadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Id ps v2 bad request response has a 2xx status code
func (o *ListIDPsV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Id ps v2 bad request response has a 3xx status code
func (o *ListIDPsV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 bad request response has a 4xx status code
func (o *ListIDPsV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Id ps v2 bad request response has a 5xx status code
func (o *ListIDPsV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 bad request response a status code equal to that given
func (o *ListIDPsV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list Id ps v2 bad request response
func (o *ListIDPsV2BadRequest) Code() int {
	return 400
}

func (o *ListIDPsV2BadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2BadRequest %s", 400, payload)
}

func (o *ListIDPsV2BadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2BadRequest %s", 400, payload)
}

func (o *ListIDPsV2BadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListIDPsV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIDPsV2Unauthorized creates a ListIDPsV2Unauthorized with default headers values
func NewListIDPsV2Unauthorized() *ListIDPsV2Unauthorized {
	return &ListIDPsV2Unauthorized{}
}

/*
ListIDPsV2Unauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListIDPsV2Unauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Id ps v2 unauthorized response has a 2xx status code
func (o *ListIDPsV2Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Id ps v2 unauthorized response has a 3xx status code
func (o *ListIDPsV2Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 unauthorized response has a 4xx status code
func (o *ListIDPsV2Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Id ps v2 unauthorized response has a 5xx status code
func (o *ListIDPsV2Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 unauthorized response a status code equal to that given
func (o *ListIDPsV2Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list Id ps v2 unauthorized response
func (o *ListIDPsV2Unauthorized) Code() int {
	return 401
}

func (o *ListIDPsV2Unauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2Unauthorized %s", 401, payload)
}

func (o *ListIDPsV2Unauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2Unauthorized %s", 401, payload)
}

func (o *ListIDPsV2Unauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListIDPsV2Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIDPsV2Forbidden creates a ListIDPsV2Forbidden with default headers values
func NewListIDPsV2Forbidden() *ListIDPsV2Forbidden {
	return &ListIDPsV2Forbidden{}
}

/*
ListIDPsV2Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ListIDPsV2Forbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Id ps v2 forbidden response has a 2xx status code
func (o *ListIDPsV2Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Id ps v2 forbidden response has a 3xx status code
func (o *ListIDPsV2Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 forbidden response has a 4xx status code
func (o *ListIDPsV2Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Id ps v2 forbidden response has a 5xx status code
func (o *ListIDPsV2Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 forbidden response a status code equal to that given
func (o *ListIDPsV2Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the list Id ps v2 forbidden response
func (o *ListIDPsV2Forbidden) Code() int {
	return 403
}

func (o *ListIDPsV2Forbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2Forbidden %s", 403, payload)
}

func (o *ListIDPsV2Forbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2Forbidden %s", 403, payload)
}

func (o *ListIDPsV2Forbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListIDPsV2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIDPsV2NotFound creates a ListIDPsV2NotFound with default headers values
func NewListIDPsV2NotFound() *ListIDPsV2NotFound {
	return &ListIDPsV2NotFound{}
}

/*
ListIDPsV2NotFound describes a response with status code 404, with default header values.

Not found
*/
type ListIDPsV2NotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Id ps v2 not found response has a 2xx status code
func (o *ListIDPsV2NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Id ps v2 not found response has a 3xx status code
func (o *ListIDPsV2NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 not found response has a 4xx status code
func (o *ListIDPsV2NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Id ps v2 not found response has a 5xx status code
func (o *ListIDPsV2NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 not found response a status code equal to that given
func (o *ListIDPsV2NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list Id ps v2 not found response
func (o *ListIDPsV2NotFound) Code() int {
	return 404
}

func (o *ListIDPsV2NotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2NotFound %s", 404, payload)
}

func (o *ListIDPsV2NotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2NotFound %s", 404, payload)
}

func (o *ListIDPsV2NotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListIDPsV2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIDPsV2TooManyRequests creates a ListIDPsV2TooManyRequests with default headers values
func NewListIDPsV2TooManyRequests() *ListIDPsV2TooManyRequests {
	return &ListIDPsV2TooManyRequests{}
}

/*
ListIDPsV2TooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type ListIDPsV2TooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Id ps v2 too many requests response has a 2xx status code
func (o *ListIDPsV2TooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Id ps v2 too many requests response has a 3xx status code
func (o *ListIDPsV2TooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Id ps v2 too many requests response has a 4xx status code
func (o *ListIDPsV2TooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Id ps v2 too many requests response has a 5xx status code
func (o *ListIDPsV2TooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this list Id ps v2 too many requests response a status code equal to that given
func (o *ListIDPsV2TooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the list Id ps v2 too many requests response
func (o *ListIDPsV2TooManyRequests) Code() int {
	return 429
}

func (o *ListIDPsV2TooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2TooManyRequests %s", 429, payload)
}

func (o *ListIDPsV2TooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /servers/{wid}/v2/idps][%d] listIdPsV2TooManyRequests %s", 429, payload)
}

func (o *ListIDPsV2TooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListIDPsV2TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
