// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthenticatorAssertionResponse The AuthenticatorAssertionResponse contains the raw authenticator assertion data and is parsed into
// [ParsedAssertionResponse].
//
// swagger:model AuthenticatorAssertionResponse
type AuthenticatorAssertionResponse struct {

	// authenticator data
	AuthenticatorData URLEncodedBase64 `json:"authenticatorData,omitempty" yaml:"authenticatorData,omitempty"`

	// client data JSON
	ClientDataJSON URLEncodedBase64 `json:"clientDataJSON,omitempty" yaml:"clientDataJSON,omitempty"`

	// signature
	Signature URLEncodedBase64 `json:"signature,omitempty" yaml:"signature,omitempty"`

	// user handle
	UserHandle URLEncodedBase64 `json:"userHandle,omitempty" yaml:"userHandle,omitempty"`
}

// Validate validates this authenticator assertion response
func (m *AuthenticatorAssertionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthenticatorData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientDataJSON(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserHandle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthenticatorAssertionResponse) validateAuthenticatorData(formats strfmt.Registry) error {
	if swag.IsZero(m.AuthenticatorData) { // not required
		return nil
	}

	if err := m.AuthenticatorData.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("authenticatorData")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("authenticatorData")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) validateClientDataJSON(formats strfmt.Registry) error {
	if swag.IsZero(m.ClientDataJSON) { // not required
		return nil
	}

	if err := m.ClientDataJSON.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("clientDataJSON")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("clientDataJSON")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) validateSignature(formats strfmt.Registry) error {
	if swag.IsZero(m.Signature) { // not required
		return nil
	}

	if err := m.Signature.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signature")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signature")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) validateUserHandle(formats strfmt.Registry) error {
	if swag.IsZero(m.UserHandle) { // not required
		return nil
	}

	if err := m.UserHandle.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("userHandle")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("userHandle")
		}
		return err
	}

	return nil
}

// ContextValidate validate this authenticator assertion response based on the context it is used
func (m *AuthenticatorAssertionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthenticatorData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClientDataJSON(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSignature(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserHandle(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthenticatorAssertionResponse) contextValidateAuthenticatorData(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.AuthenticatorData) { // not required
		return nil
	}

	if err := m.AuthenticatorData.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("authenticatorData")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("authenticatorData")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) contextValidateClientDataJSON(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.ClientDataJSON) { // not required
		return nil
	}

	if err := m.ClientDataJSON.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("clientDataJSON")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("clientDataJSON")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) contextValidateSignature(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Signature) { // not required
		return nil
	}

	if err := m.Signature.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("signature")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("signature")
		}
		return err
	}

	return nil
}

func (m *AuthenticatorAssertionResponse) contextValidateUserHandle(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.UserHandle) { // not required
		return nil
	}

	if err := m.UserHandle.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("userHandle")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("userHandle")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthenticatorAssertionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthenticatorAssertionResponse) UnmarshalBinary(b []byte) error {
	var res AuthenticatorAssertionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
