// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CredentialParameter CredentialParameter is the credential type and algorithm
// that the relying party wants the authenticator to create.
//
// swagger:model CredentialParameter
type CredentialParameter struct {

	// alg
	Alg COSEAlgorithmIdentifier `json:"alg,omitempty" yaml:"alg,omitempty"`

	// type
	Type CredentialType `json:"type,omitempty" yaml:"type,omitempty"`
}

// Validate validates this credential parameter
func (m *CredentialParameter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlg(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialParameter) validateAlg(formats strfmt.Registry) error {
	if swag.IsZero(m.Alg) { // not required
		return nil
	}

	if err := m.Alg.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alg")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alg")
		}
		return err
	}

	return nil
}

func (m *CredentialParameter) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("type")
		}
		return err
	}

	return nil
}

// ContextValidate validate this credential parameter based on the context it is used
func (m *CredentialParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAlg(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialParameter) contextValidateAlg(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Alg) { // not required
		return nil
	}

	if err := m.Alg.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("alg")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("alg")
		}
		return err
	}

	return nil
}

func (m *CredentialParameter) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CredentialParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialParameter) UnmarshalBinary(b []byte) error {
	var res CredentialParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
