// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CredentialPropertiesOutput CredentialPropertiesOutput represents the CredentialPropertiesOutput IDL. The editor's draft defines no member
// other than rk.
//
// Specification: §10.1.3. Credential Properties Extension (https://www.w3.org/TR/webauthn-3/#sctn-authenticator-credential-properties-extension)
//
// swagger:model CredentialPropertiesOutput
type CredentialPropertiesOutput struct {

	// RK reports whether the created credential is a client-side discoverable credential. A false value is
	// meaningful and distinct from the client not reporting the property at all.
	Rk bool `json:"rk,omitempty" yaml:"rk,omitempty"`
}

// Validate validates this credential properties output
func (m *CredentialPropertiesOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this credential properties output based on context it is used
func (m *CredentialPropertiesOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CredentialPropertiesOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialPropertiesOutput) UnmarshalBinary(b []byte) error {
	var res CredentialPropertiesOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
