// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExtensionSchemaData extension schema data
//
// swagger:model ExtensionSchemaData
type ExtensionSchemaData struct {

	// additional identifiers
	AdditionalIdentifiers []*SCIMv2Identifier `json:"additionalIdentifiers" yaml:"additionalIdentifiers"`

	// business metadata
	BusinessMetadata map[string]interface{} `json:"businessMetadata,omitempty" yaml:"businessMetadata,omitempty"`

	// emails
	Emails []*SCIMv2ExtensionEmail `json:"emails" yaml:"emails"`

	// metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// payload
	Payload map[string]interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`

	// phone numbers
	PhoneNumbers []*SCIMv2ExtensionPhoneNumber `json:"phoneNumbers" yaml:"phoneNumbers"`
}

// Validate validates this extension schema data
func (m *ExtensionSchemaData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdditionalIdentifiers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhoneNumbers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtensionSchemaData) validateAdditionalIdentifiers(formats strfmt.Registry) error {
	if swag.IsZero(m.AdditionalIdentifiers) { // not required
		return nil
	}

	for i := 0; i < len(m.AdditionalIdentifiers); i++ {
		if swag.IsZero(m.AdditionalIdentifiers[i]) { // not required
			continue
		}

		if m.AdditionalIdentifiers[i] != nil {
			if err := m.AdditionalIdentifiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additionalIdentifiers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additionalIdentifiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ExtensionSchemaData) validateEmails(formats strfmt.Registry) error {
	if swag.IsZero(m.Emails) { // not required
		return nil
	}

	for i := 0; i < len(m.Emails); i++ {
		if swag.IsZero(m.Emails[i]) { // not required
			continue
		}

		if m.Emails[i] != nil {
			if err := m.Emails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("emails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("emails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ExtensionSchemaData) validatePhoneNumbers(formats strfmt.Registry) error {
	if swag.IsZero(m.PhoneNumbers) { // not required
		return nil
	}

	for i := 0; i < len(m.PhoneNumbers); i++ {
		if swag.IsZero(m.PhoneNumbers[i]) { // not required
			continue
		}

		if m.PhoneNumbers[i] != nil {
			if err := m.PhoneNumbers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("phoneNumbers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("phoneNumbers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this extension schema data based on the context it is used
func (m *ExtensionSchemaData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdditionalIdentifiers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEmails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePhoneNumbers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtensionSchemaData) contextValidateAdditionalIdentifiers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdditionalIdentifiers); i++ {

		if m.AdditionalIdentifiers[i] != nil {

			if swag.IsZero(m.AdditionalIdentifiers[i]) { // not required
				return nil
			}

			if err := m.AdditionalIdentifiers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additionalIdentifiers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additionalIdentifiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ExtensionSchemaData) contextValidateEmails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Emails); i++ {

		if m.Emails[i] != nil {

			if swag.IsZero(m.Emails[i]) { // not required
				return nil
			}

			if err := m.Emails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("emails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("emails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ExtensionSchemaData) contextValidatePhoneNumbers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PhoneNumbers); i++ {

		if m.PhoneNumbers[i] != nil {

			if swag.IsZero(m.PhoneNumbers[i]) { // not required
				return nil
			}

			if err := m.PhoneNumbers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("phoneNumbers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("phoneNumbers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExtensionSchemaData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtensionSchemaData) UnmarshalBinary(b []byte) error {
	var res ExtensionSchemaData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
