// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PublicKeyCredentialHints PublicKeyCredentialHints represents an entry of the hints member, which conveys the Relying Party's belief about
// how the user will satisfy the request, in descending order of preference.
//
// The IDL types the hints member as a sequence of strings rather than as this enumeration, and requires clients to
// ignore values they do not recognise, so values are deliberately not validated against the constants below: a
// Relying Party may send a hint ratified after this release, or one a particular user agent understands. Clients
// also ignore the second and later appearances of a repeated hint.
//
// Hints may contradict the authenticator attachment and the transports of the allowed credentials. Where they do,
// a client which implements hints gives the hints precedence; see
// [PublicKeyCredentialHints.AuthenticatorAttachment] for how a registration ceremony pairs the two for the benefit
// of clients which do not.
//
// WebAuthn Level 3.
//
// Specification: §5.8.7. User-agent Hints Enumeration (https://www.w3.org/TR/webauthn-3/#enum-hints)
//
// swagger:model PublicKeyCredentialHints
type PublicKeyCredentialHints string

// Validate validates this public key credential hints
func (m PublicKeyCredentialHints) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this public key credential hints based on context it is used
func (m PublicKeyCredentialHints) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
