// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SCIMv2IdentifierType s c i mv2 identifier type
//
// swagger:model SCIMv2IdentifierType
type SCIMv2IdentifierType string

// Validate validates this s c i mv2 identifier type
func (m SCIMv2IdentifierType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this s c i mv2 identifier type based on context it is used
func (m SCIMv2IdentifierType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
