// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SCIMv2Patch s c i mv2 patch
//
// swagger:model SCIMv2Patch
type SCIMv2Patch struct {

	// operations
	Operations Rfc6902PatchOperations `json:"Operations,omitempty" yaml:"Operations,omitempty"`

	// example ["urn:ietf:params:scim:api:messages:2.0:PatchOp"]
	Schemas []string `json:"schemas" yaml:"schemas"`
}

// Validate validates this s c i mv2 patch
func (m *SCIMv2Patch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SCIMv2Patch) validateOperations(formats strfmt.Registry) error {
	if swag.IsZero(m.Operations) { // not required
		return nil
	}

	if err := m.Operations.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Operations")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("Operations")
		}
		return err
	}

	return nil
}

// ContextValidate validate this s c i mv2 patch based on the context it is used
func (m *SCIMv2Patch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOperations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SCIMv2Patch) contextValidateOperations(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Operations.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Operations")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("Operations")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SCIMv2Patch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SCIMv2Patch) UnmarshalBinary(b []byte) error {
	var res SCIMv2Patch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
