// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchemaExtension schema extension
//
// swagger:model SchemaExtension
type SchemaExtension struct {

	// required
	Required bool `json:"required,omitempty" yaml:"required,omitempty"`

	// schema
	Schema string `json:"schema,omitempty" yaml:"schema,omitempty"`
}

// Validate validates this schema extension
func (m *SchemaExtension) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this schema extension based on context it is used
func (m *SchemaExtension) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchemaExtension) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchemaExtension) UnmarshalBinary(b []byte) error {
	var res SchemaExtension
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
