// Code generated by go-swagger; DO NOT EDIT.

package o_t_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identityself/models"
)

// NewCompleteAddressVerificationParams creates a new CompleteAddressVerificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCompleteAddressVerificationParams() *CompleteAddressVerificationParams {
	return &CompleteAddressVerificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCompleteAddressVerificationParamsWithTimeout creates a new CompleteAddressVerificationParams object
// with the ability to set a timeout on a request.
func NewCompleteAddressVerificationParamsWithTimeout(timeout time.Duration) *CompleteAddressVerificationParams {
	return &CompleteAddressVerificationParams{
		timeout: timeout,
	}
}

// NewCompleteAddressVerificationParamsWithContext creates a new CompleteAddressVerificationParams object
// with the ability to set a context for a request.
func NewCompleteAddressVerificationParamsWithContext(ctx context.Context) *CompleteAddressVerificationParams {
	return &CompleteAddressVerificationParams{
		Context: ctx,
	}
}

// NewCompleteAddressVerificationParamsWithHTTPClient creates a new CompleteAddressVerificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCompleteAddressVerificationParamsWithHTTPClient(client *http.Client) *CompleteAddressVerificationParams {
	return &CompleteAddressVerificationParams{
		HTTPClient: client,
	}
}

/*
CompleteAddressVerificationParams contains all the parameters to send to the API endpoint

	for the complete address verification operation.

	Typically these are written to a http.Request.
*/
type CompleteAddressVerificationParams struct {

	// CompleteAddressVerification.
	CompleteAddressVerification *models.CompleteAddressVerification

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the complete address verification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompleteAddressVerificationParams) WithDefaults() *CompleteAddressVerificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the complete address verification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompleteAddressVerificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the complete address verification params
func (o *CompleteAddressVerificationParams) WithTimeout(timeout time.Duration) *CompleteAddressVerificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the complete address verification params
func (o *CompleteAddressVerificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the complete address verification params
func (o *CompleteAddressVerificationParams) WithContext(ctx context.Context) *CompleteAddressVerificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the complete address verification params
func (o *CompleteAddressVerificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the complete address verification params
func (o *CompleteAddressVerificationParams) WithHTTPClient(client *http.Client) *CompleteAddressVerificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the complete address verification params
func (o *CompleteAddressVerificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCompleteAddressVerification adds the completeAddressVerification to the complete address verification params
func (o *CompleteAddressVerificationParams) WithCompleteAddressVerification(completeAddressVerification *models.CompleteAddressVerification) *CompleteAddressVerificationParams {
	o.SetCompleteAddressVerification(completeAddressVerification)
	return o
}

// SetCompleteAddressVerification adds the completeAddressVerification to the complete address verification params
func (o *CompleteAddressVerificationParams) SetCompleteAddressVerification(completeAddressVerification *models.CompleteAddressVerification) {
	o.CompleteAddressVerification = completeAddressVerification
}

// WithIfMatch adds the ifMatch to the complete address verification params
func (o *CompleteAddressVerificationParams) WithIfMatch(ifMatch *string) *CompleteAddressVerificationParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the complete address verification params
func (o *CompleteAddressVerificationParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithXCorrelationID adds the xCorrelationID to the complete address verification params
func (o *CompleteAddressVerificationParams) WithXCorrelationID(xCorrelationID *string) *CompleteAddressVerificationParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the complete address verification params
func (o *CompleteAddressVerificationParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the complete address verification params
func (o *CompleteAddressVerificationParams) WithXIdempotencyKey(xIdempotencyKey *string) *CompleteAddressVerificationParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the complete address verification params
func (o *CompleteAddressVerificationParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *CompleteAddressVerificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CompleteAddressVerification != nil {
		if err := r.SetBodyParam(o.CompleteAddressVerification); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
