// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPolicyExecutionPointsParams creates a new ListPolicyExecutionPointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPolicyExecutionPointsParams() *ListPolicyExecutionPointsParams {
	return &ListPolicyExecutionPointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPolicyExecutionPointsParamsWithTimeout creates a new ListPolicyExecutionPointsParams object
// with the ability to set a timeout on a request.
func NewListPolicyExecutionPointsParamsWithTimeout(timeout time.Duration) *ListPolicyExecutionPointsParams {
	return &ListPolicyExecutionPointsParams{
		timeout: timeout,
	}
}

// NewListPolicyExecutionPointsParamsWithContext creates a new ListPolicyExecutionPointsParams object
// with the ability to set a context for a request.
func NewListPolicyExecutionPointsParamsWithContext(ctx context.Context) *ListPolicyExecutionPointsParams {
	return &ListPolicyExecutionPointsParams{
		Context: ctx,
	}
}

// NewListPolicyExecutionPointsParamsWithHTTPClient creates a new ListPolicyExecutionPointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPolicyExecutionPointsParamsWithHTTPClient(client *http.Client) *ListPolicyExecutionPointsParams {
	return &ListPolicyExecutionPointsParams{
		HTTPClient: client,
	}
}

/*
ListPolicyExecutionPointsParams contains all the parameters to send to the API endpoint

	for the list policy execution points operation.

	Typically these are written to a http.Request.
*/
type ListPolicyExecutionPointsParams struct {

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list policy execution points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPolicyExecutionPointsParams) WithDefaults() *ListPolicyExecutionPointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list policy execution points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPolicyExecutionPointsParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := ListPolicyExecutionPointsParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithTimeout(timeout time.Duration) *ListPolicyExecutionPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithContext(ctx context.Context) *ListPolicyExecutionPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithHTTPClient(client *http.Client) *ListPolicyExecutionPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithIfMatch(ifMatch *string) *ListPolicyExecutionPointsParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithWid(wid string) *ListPolicyExecutionPointsParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithXCorrelationID(xCorrelationID *string) *ListPolicyExecutionPointsParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) WithXIdempotencyKey(xIdempotencyKey *string) *ListPolicyExecutionPointsParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the list policy execution points params
func (o *ListPolicyExecutionPointsParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *ListPolicyExecutionPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
