// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClientTokenExchangeConfiguration client token exchange configuration
//
// swagger:model ClientTokenExchangeConfiguration
type ClientTokenExchangeConfiguration struct {

	// Additional actor token claims
	//
	// Claims from the actor token that will be injected into the exchanged token under the `act` claim.
	//
	// Applies for the token exchange delegation flow only.
	ActorClaims []string `json:"actor_claims" yaml:"actor_claims"`

	// ID-JAG targets with optional client ID and audience tenant overrides. Audiences must be unique.
	IDJagTargets []*ClientIDJAGTarget `json:"id_jag_targets" yaml:"id_jag_targets"`
}

// Validate validates this client token exchange configuration
func (m *ClientTokenExchangeConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIDJagTargets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientTokenExchangeConfiguration) validateIDJagTargets(formats strfmt.Registry) error {
	if swag.IsZero(m.IDJagTargets) { // not required
		return nil
	}

	for i := 0; i < len(m.IDJagTargets); i++ {
		if swag.IsZero(m.IDJagTargets[i]) { // not required
			continue
		}

		if m.IDJagTargets[i] != nil {
			if err := m.IDJagTargets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("id_jag_targets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("id_jag_targets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this client token exchange configuration based on the context it is used
func (m *ClientTokenExchangeConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIDJagTargets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientTokenExchangeConfiguration) contextValidateIDJagTargets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IDJagTargets); i++ {

		if m.IDJagTargets[i] != nil {

			if swag.IsZero(m.IDJagTargets[i]) { // not required
				return nil
			}

			if err := m.IDJagTargets[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("id_jag_targets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("id_jag_targets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClientTokenExchangeConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientTokenExchangeConfiguration) UnmarshalBinary(b []byte) error {
	var res ClientTokenExchangeConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
