// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// WorkforceProvisioningStatus workforce provisioning status
//
// swagger:model WorkforceProvisioningStatus
type WorkforceProvisioningStatus string

// Validate validates this workforce provisioning status
func (m WorkforceProvisioningStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this workforce provisioning status based on context it is used
func (m WorkforceProvisioningStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
