// Code generated by go-swagger; DO NOT EDIT.

package phone_provider_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// DeletePhoneProviderConfigReader is a Reader for the DeletePhoneProviderConfig structure.
type DeletePhoneProviderConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePhoneProviderConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePhoneProviderConfigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeletePhoneProviderConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeletePhoneProviderConfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeletePhoneProviderConfigTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /phone-provider-config] deletePhoneProviderConfig", response, response.Code())
	}
}

// NewDeletePhoneProviderConfigNoContent creates a DeletePhoneProviderConfigNoContent with default headers values
func NewDeletePhoneProviderConfigNoContent() *DeletePhoneProviderConfigNoContent {
	return &DeletePhoneProviderConfigNoContent{}
}

/*
DeletePhoneProviderConfigNoContent describes a response with status code 204, with default header values.

	Phone provider config has been deleted
*/
type DeletePhoneProviderConfigNoContent struct {
}

// IsSuccess returns true when this delete phone provider config no content response has a 2xx status code
func (o *DeletePhoneProviderConfigNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete phone provider config no content response has a 3xx status code
func (o *DeletePhoneProviderConfigNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete phone provider config no content response has a 4xx status code
func (o *DeletePhoneProviderConfigNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete phone provider config no content response has a 5xx status code
func (o *DeletePhoneProviderConfigNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete phone provider config no content response a status code equal to that given
func (o *DeletePhoneProviderConfigNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete phone provider config no content response
func (o *DeletePhoneProviderConfigNoContent) Code() int {
	return 204
}

func (o *DeletePhoneProviderConfigNoContent) Error() string {
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigNoContent", 204)
}

func (o *DeletePhoneProviderConfigNoContent) String() string {
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigNoContent", 204)
}

func (o *DeletePhoneProviderConfigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePhoneProviderConfigUnauthorized creates a DeletePhoneProviderConfigUnauthorized with default headers values
func NewDeletePhoneProviderConfigUnauthorized() *DeletePhoneProviderConfigUnauthorized {
	return &DeletePhoneProviderConfigUnauthorized{}
}

/*
DeletePhoneProviderConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeletePhoneProviderConfigUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete phone provider config unauthorized response has a 2xx status code
func (o *DeletePhoneProviderConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete phone provider config unauthorized response has a 3xx status code
func (o *DeletePhoneProviderConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete phone provider config unauthorized response has a 4xx status code
func (o *DeletePhoneProviderConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete phone provider config unauthorized response has a 5xx status code
func (o *DeletePhoneProviderConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete phone provider config unauthorized response a status code equal to that given
func (o *DeletePhoneProviderConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete phone provider config unauthorized response
func (o *DeletePhoneProviderConfigUnauthorized) Code() int {
	return 401
}

func (o *DeletePhoneProviderConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigUnauthorized %s", 401, payload)
}

func (o *DeletePhoneProviderConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigUnauthorized %s", 401, payload)
}

func (o *DeletePhoneProviderConfigUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePhoneProviderConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePhoneProviderConfigForbidden creates a DeletePhoneProviderConfigForbidden with default headers values
func NewDeletePhoneProviderConfigForbidden() *DeletePhoneProviderConfigForbidden {
	return &DeletePhoneProviderConfigForbidden{}
}

/*
DeletePhoneProviderConfigForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeletePhoneProviderConfigForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete phone provider config forbidden response has a 2xx status code
func (o *DeletePhoneProviderConfigForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete phone provider config forbidden response has a 3xx status code
func (o *DeletePhoneProviderConfigForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete phone provider config forbidden response has a 4xx status code
func (o *DeletePhoneProviderConfigForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete phone provider config forbidden response has a 5xx status code
func (o *DeletePhoneProviderConfigForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete phone provider config forbidden response a status code equal to that given
func (o *DeletePhoneProviderConfigForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete phone provider config forbidden response
func (o *DeletePhoneProviderConfigForbidden) Code() int {
	return 403
}

func (o *DeletePhoneProviderConfigForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigForbidden %s", 403, payload)
}

func (o *DeletePhoneProviderConfigForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigForbidden %s", 403, payload)
}

func (o *DeletePhoneProviderConfigForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePhoneProviderConfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePhoneProviderConfigTooManyRequests creates a DeletePhoneProviderConfigTooManyRequests with default headers values
func NewDeletePhoneProviderConfigTooManyRequests() *DeletePhoneProviderConfigTooManyRequests {
	return &DeletePhoneProviderConfigTooManyRequests{}
}

/*
DeletePhoneProviderConfigTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type DeletePhoneProviderConfigTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete phone provider config too many requests response has a 2xx status code
func (o *DeletePhoneProviderConfigTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete phone provider config too many requests response has a 3xx status code
func (o *DeletePhoneProviderConfigTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete phone provider config too many requests response has a 4xx status code
func (o *DeletePhoneProviderConfigTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete phone provider config too many requests response has a 5xx status code
func (o *DeletePhoneProviderConfigTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this delete phone provider config too many requests response a status code equal to that given
func (o *DeletePhoneProviderConfigTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the delete phone provider config too many requests response
func (o *DeletePhoneProviderConfigTooManyRequests) Code() int {
	return 429
}

func (o *DeletePhoneProviderConfigTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigTooManyRequests %s", 429, payload)
}

func (o *DeletePhoneProviderConfigTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /phone-provider-config][%d] deletePhoneProviderConfigTooManyRequests %s", 429, payload)
}

func (o *DeletePhoneProviderConfigTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePhoneProviderConfigTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
