// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GenericError Error response
//
// swagger:model genericError
type GenericError struct {

	// error cause
	Cause string `json:"cause,omitempty" yaml:"cause,omitempty"`

	// error details
	Details interface{} `json:"details,omitempty" yaml:"details,omitempty"`

	// error
	// Example: The requested resource could not be found
	// Required: true
	Error string `json:"error" yaml:"error"`

	// error description
	ErrorDescription string `json:"error_description,omitempty" yaml:"error_description,omitempty"`

	// error hint
	// Example: Object with ID 12345 does not exist
	ErrorHint string `json:"error_hint,omitempty" yaml:"error_hint,omitempty"`

	// Code represents the error status code (404, 403, 401, ...).
	// Example: 404
	StatusCode int64 `json:"status_code,omitempty" yaml:"status_code,omitempty"`
}

// Validate validates this generic error
func (m *GenericError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GenericError) validateError(formats strfmt.Registry) error {

	if err := validate.RequiredString("error", "body", m.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this generic error based on context it is used
func (m *GenericError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GenericError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GenericError) UnmarshalBinary(b []byte) error {
	var res GenericError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
