definitions:
  Error:
    description: HTTP error response
    properties:
      details:
        type: object
        x-nullable: false
      error:
        type: string
        x-nullable: false
      error_code:
        type: string
        x-nullable: false
      status_code:
        format: int64
        type: integer
        x-nullable: false
    type: object
  Styling:
    properties:
      colors:
        properties:
          background:
            type: string
            x-nullable: false
          header:
            type: string
            x-nullable: false
          primary:
            type: string
            x-nullable: false
        type: object
        x-nullable: false
      font_url:
        type: string
        x-nullable: false
      logo_size:
        type: string
        x-nullable: false
      logo_url:
        type: string
        x-nullable: false
    type: object
info:
  title: ""
  version: ""
paths:
  /{aid}/styling:
    get:
      operationId: getStyling
      parameters:
      - default: admin
        description: Authorization server id
        in: path
        name: aid
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/Styling'
        "404":
          $ref: '#/responses/notFoundHTTPError'
      summary: Get styling for a tenant.
      tags:
      - web
responses:
  Styling:
    description: Styling
    schema:
      $ref: '#/definitions/Styling'
  badRequestHTTPError:
    description: Bad request
    schema:
      $ref: '#/definitions/Error'
  conflictHTTPError:
    description: Conflict
    schema:
      $ref: '#/definitions/Error'
  forbiddenHTTPError:
    description: Forbidden
    schema:
      $ref: '#/definitions/Error'
  internalServerErrorHTTPError:
    description: Internal server error
    schema:
      $ref: '#/definitions/Error'
  methodNotAllowedHTTPError:
    description: Method not allowed
    schema:
      $ref: '#/definitions/Error'
  notFoundHTTPError:
    description: Not found
    schema:
      $ref: '#/definitions/Error'
  payloadTooLargeHTTPError:
    description: Payload too large
    schema:
      $ref: '#/definitions/Error'
  preconditionFailedHTTPError:
    description: Precondition failed
    schema:
      $ref: '#/definitions/Error'
  tooManyRequestsHTTPError:
    description: Too many requests
    schema:
      $ref: '#/definitions/Error'
  unauthorizedHTTPError:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
  unprocessableEntityHTTPError:
    description: Unprocessable entity
    schema:
      $ref: '#/definitions/Error'
swagger: "2.0"
