// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// NewCreateCognitoIDPParams creates a new CreateCognitoIDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCognitoIDPParams() *CreateCognitoIDPParams {
	return &CreateCognitoIDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCognitoIDPParamsWithTimeout creates a new CreateCognitoIDPParams object
// with the ability to set a timeout on a request.
func NewCreateCognitoIDPParamsWithTimeout(timeout time.Duration) *CreateCognitoIDPParams {
	return &CreateCognitoIDPParams{
		timeout: timeout,
	}
}

// NewCreateCognitoIDPParamsWithContext creates a new CreateCognitoIDPParams object
// with the ability to set a context for a request.
func NewCreateCognitoIDPParamsWithContext(ctx context.Context) *CreateCognitoIDPParams {
	return &CreateCognitoIDPParams{
		Context: ctx,
	}
}

// NewCreateCognitoIDPParamsWithHTTPClient creates a new CreateCognitoIDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCognitoIDPParamsWithHTTPClient(client *http.Client) *CreateCognitoIDPParams {
	return &CreateCognitoIDPParams{
		HTTPClient: client,
	}
}

/*
CreateCognitoIDPParams contains all the parameters to send to the API endpoint

	for the create cognito ID p operation.

	Typically these are written to a http.Request.
*/
type CreateCognitoIDPParams struct {

	/* CognitoIDP.

	   CognitoIDP
	*/
	CognitoIDP *models.CognitoIDP

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create cognito ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCognitoIDPParams) WithDefaults() *CreateCognitoIDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create cognito ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCognitoIDPParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := CreateCognitoIDPParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithTimeout(timeout time.Duration) *CreateCognitoIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithContext(ctx context.Context) *CreateCognitoIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithHTTPClient(client *http.Client) *CreateCognitoIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCognitoIDP adds the cognitoIDP to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithCognitoIDP(cognitoIDP *models.CognitoIDP) *CreateCognitoIDPParams {
	o.SetCognitoIDP(cognitoIDP)
	return o
}

// SetCognitoIDP adds the cognitoIdP to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetCognitoIDP(cognitoIDP *models.CognitoIDP) {
	o.CognitoIDP = cognitoIDP
}

// WithIfMatch adds the ifMatch to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithIfMatch(ifMatch *string) *CreateCognitoIDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithWid(wid string) *CreateCognitoIDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithXCorrelationID(xCorrelationID *string) *CreateCognitoIDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the create cognito ID p params
func (o *CreateCognitoIDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *CreateCognitoIDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the create cognito ID p params
func (o *CreateCognitoIDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCognitoIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CognitoIDP != nil {
		if err := r.SetBodyParam(o.CognitoIDP); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
