// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// NewCreateWorkforceIDPParams creates a new CreateWorkforceIDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateWorkforceIDPParams() *CreateWorkforceIDPParams {
	return &CreateWorkforceIDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWorkforceIDPParamsWithTimeout creates a new CreateWorkforceIDPParams object
// with the ability to set a timeout on a request.
func NewCreateWorkforceIDPParamsWithTimeout(timeout time.Duration) *CreateWorkforceIDPParams {
	return &CreateWorkforceIDPParams{
		timeout: timeout,
	}
}

// NewCreateWorkforceIDPParamsWithContext creates a new CreateWorkforceIDPParams object
// with the ability to set a context for a request.
func NewCreateWorkforceIDPParamsWithContext(ctx context.Context) *CreateWorkforceIDPParams {
	return &CreateWorkforceIDPParams{
		Context: ctx,
	}
}

// NewCreateWorkforceIDPParamsWithHTTPClient creates a new CreateWorkforceIDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateWorkforceIDPParamsWithHTTPClient(client *http.Client) *CreateWorkforceIDPParams {
	return &CreateWorkforceIDPParams{
		HTTPClient: client,
	}
}

/*
CreateWorkforceIDPParams contains all the parameters to send to the API endpoint

	for the create workforce ID p operation.

	Typically these are written to a http.Request.
*/
type CreateWorkforceIDPParams struct {

	/* WorkforceIDP.

	   WorkforceIDP
	*/
	WorkforceIDP *models.WorkforceIDP

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create workforce ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkforceIDPParams) WithDefaults() *CreateWorkforceIDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create workforce ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWorkforceIDPParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := CreateWorkforceIDPParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithTimeout(timeout time.Duration) *CreateWorkforceIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithContext(ctx context.Context) *CreateWorkforceIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithHTTPClient(client *http.Client) *CreateWorkforceIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkforceIDP adds the workforceIDP to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithWorkforceIDP(workforceIDP *models.WorkforceIDP) *CreateWorkforceIDPParams {
	o.SetWorkforceIDP(workforceIDP)
	return o
}

// SetWorkforceIDP adds the workforceIdP to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetWorkforceIDP(workforceIDP *models.WorkforceIDP) {
	o.WorkforceIDP = workforceIDP
}

// WithIfMatch adds the ifMatch to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithIfMatch(ifMatch *string) *CreateWorkforceIDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithWid(wid string) *CreateWorkforceIDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithXCorrelationID(xCorrelationID *string) *CreateWorkforceIDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the create workforce ID p params
func (o *CreateWorkforceIDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *CreateWorkforceIDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the create workforce ID p params
func (o *CreateWorkforceIDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWorkforceIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.WorkforceIDP != nil {
		if err := r.SetBodyParam(o.WorkforceIDP); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
