// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOktaV2IDPParams creates a new GetOktaV2IDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOktaV2IDPParams() *GetOktaV2IDPParams {
	return &GetOktaV2IDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOktaV2IDPParamsWithTimeout creates a new GetOktaV2IDPParams object
// with the ability to set a timeout on a request.
func NewGetOktaV2IDPParamsWithTimeout(timeout time.Duration) *GetOktaV2IDPParams {
	return &GetOktaV2IDPParams{
		timeout: timeout,
	}
}

// NewGetOktaV2IDPParamsWithContext creates a new GetOktaV2IDPParams object
// with the ability to set a context for a request.
func NewGetOktaV2IDPParamsWithContext(ctx context.Context) *GetOktaV2IDPParams {
	return &GetOktaV2IDPParams{
		Context: ctx,
	}
}

// NewGetOktaV2IDPParamsWithHTTPClient creates a new GetOktaV2IDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOktaV2IDPParamsWithHTTPClient(client *http.Client) *GetOktaV2IDPParams {
	return &GetOktaV2IDPParams{
		HTTPClient: client,
	}
}

/*
GetOktaV2IDPParams contains all the parameters to send to the API endpoint

	for the get okta v2 ID p operation.

	Typically these are written to a http.Request.
*/
type GetOktaV2IDPParams struct {

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Iid.

	   IDP id
	*/
	Iid string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get okta v2 ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOktaV2IDPParams) WithDefaults() *GetOktaV2IDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get okta v2 ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOktaV2IDPParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := GetOktaV2IDPParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithTimeout(timeout time.Duration) *GetOktaV2IDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithContext(ctx context.Context) *GetOktaV2IDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithHTTPClient(client *http.Client) *GetOktaV2IDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithIfMatch(ifMatch *string) *GetOktaV2IDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIid adds the iid to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithIid(iid string) *GetOktaV2IDPParams {
	o.SetIid(iid)
	return o
}

// SetIid adds the iid to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetIid(iid string) {
	o.Iid = iid
}

// WithWid adds the wid to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithWid(wid string) *GetOktaV2IDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithXCorrelationID(xCorrelationID *string) *GetOktaV2IDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *GetOktaV2IDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the get okta v2 ID p params
func (o *GetOktaV2IDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetOktaV2IDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param iid
	if err := r.SetPathParam("iid", o.Iid); err != nil {
		return err
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
