// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetXIDPParams creates a new GetXIDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetXIDPParams() *GetXIDPParams {
	return &GetXIDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetXIDPParamsWithTimeout creates a new GetXIDPParams object
// with the ability to set a timeout on a request.
func NewGetXIDPParamsWithTimeout(timeout time.Duration) *GetXIDPParams {
	return &GetXIDPParams{
		timeout: timeout,
	}
}

// NewGetXIDPParamsWithContext creates a new GetXIDPParams object
// with the ability to set a context for a request.
func NewGetXIDPParamsWithContext(ctx context.Context) *GetXIDPParams {
	return &GetXIDPParams{
		Context: ctx,
	}
}

// NewGetXIDPParamsWithHTTPClient creates a new GetXIDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetXIDPParamsWithHTTPClient(client *http.Client) *GetXIDPParams {
	return &GetXIDPParams{
		HTTPClient: client,
	}
}

/*
GetXIDPParams contains all the parameters to send to the API endpoint

	for the get x ID p operation.

	Typically these are written to a http.Request.
*/
type GetXIDPParams struct {

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Iid.

	   IDP id
	*/
	Iid string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get x ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetXIDPParams) WithDefaults() *GetXIDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get x ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetXIDPParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := GetXIDPParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get x ID p params
func (o *GetXIDPParams) WithTimeout(timeout time.Duration) *GetXIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get x ID p params
func (o *GetXIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get x ID p params
func (o *GetXIDPParams) WithContext(ctx context.Context) *GetXIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get x ID p params
func (o *GetXIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get x ID p params
func (o *GetXIDPParams) WithHTTPClient(client *http.Client) *GetXIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get x ID p params
func (o *GetXIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the get x ID p params
func (o *GetXIDPParams) WithIfMatch(ifMatch *string) *GetXIDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the get x ID p params
func (o *GetXIDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIid adds the iid to the get x ID p params
func (o *GetXIDPParams) WithIid(iid string) *GetXIDPParams {
	o.SetIid(iid)
	return o
}

// SetIid adds the iid to the get x ID p params
func (o *GetXIDPParams) SetIid(iid string) {
	o.Iid = iid
}

// WithWid adds the wid to the get x ID p params
func (o *GetXIDPParams) WithWid(wid string) *GetXIDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the get x ID p params
func (o *GetXIDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the get x ID p params
func (o *GetXIDPParams) WithXCorrelationID(xCorrelationID *string) *GetXIDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the get x ID p params
func (o *GetXIDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the get x ID p params
func (o *GetXIDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *GetXIDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the get x ID p params
func (o *GetXIDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetXIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param iid
	if err := r.SetPathParam("iid", o.Iid); err != nil {
		return err
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
