// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// UpdateOktaV2IDPReader is a Reader for the UpdateOktaV2IDP structure.
type UpdateOktaV2IDPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOktaV2IDPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOktaV2IDPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateOktaV2IDPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateOktaV2IDPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateOktaV2IDPForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateOktaV2IDPNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateOktaV2IDPUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateOktaV2IDPTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /servers/{wid}/idps/okta_v2/{iid}] updateOktaV2IDP", response, response.Code())
	}
}

// NewUpdateOktaV2IDPOK creates a UpdateOktaV2IDPOK with default headers values
func NewUpdateOktaV2IDPOK() *UpdateOktaV2IDPOK {
	return &UpdateOktaV2IDPOK{}
}

/*
UpdateOktaV2IDPOK describes a response with status code 200, with default header values.

OktaV2IDP
*/
type UpdateOktaV2IDPOK struct {
	Payload *models.OktaV2IDP
}

// IsSuccess returns true when this update okta v2 Id p o k response has a 2xx status code
func (o *UpdateOktaV2IDPOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update okta v2 Id p o k response has a 3xx status code
func (o *UpdateOktaV2IDPOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p o k response has a 4xx status code
func (o *UpdateOktaV2IDPOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update okta v2 Id p o k response has a 5xx status code
func (o *UpdateOktaV2IDPOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p o k response a status code equal to that given
func (o *UpdateOktaV2IDPOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update okta v2 Id p o k response
func (o *UpdateOktaV2IDPOK) Code() int {
	return 200
}

func (o *UpdateOktaV2IDPOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPOK %s", 200, payload)
}

func (o *UpdateOktaV2IDPOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPOK %s", 200, payload)
}

func (o *UpdateOktaV2IDPOK) GetPayload() *models.OktaV2IDP {
	return o.Payload
}

func (o *UpdateOktaV2IDPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OktaV2IDP)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPBadRequest creates a UpdateOktaV2IDPBadRequest with default headers values
func NewUpdateOktaV2IDPBadRequest() *UpdateOktaV2IDPBadRequest {
	return &UpdateOktaV2IDPBadRequest{}
}

/*
UpdateOktaV2IDPBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type UpdateOktaV2IDPBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p bad request response has a 2xx status code
func (o *UpdateOktaV2IDPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p bad request response has a 3xx status code
func (o *UpdateOktaV2IDPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p bad request response has a 4xx status code
func (o *UpdateOktaV2IDPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p bad request response has a 5xx status code
func (o *UpdateOktaV2IDPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p bad request response a status code equal to that given
func (o *UpdateOktaV2IDPBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update okta v2 Id p bad request response
func (o *UpdateOktaV2IDPBadRequest) Code() int {
	return 400
}

func (o *UpdateOktaV2IDPBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPBadRequest %s", 400, payload)
}

func (o *UpdateOktaV2IDPBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPBadRequest %s", 400, payload)
}

func (o *UpdateOktaV2IDPBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPUnauthorized creates a UpdateOktaV2IDPUnauthorized with default headers values
func NewUpdateOktaV2IDPUnauthorized() *UpdateOktaV2IDPUnauthorized {
	return &UpdateOktaV2IDPUnauthorized{}
}

/*
UpdateOktaV2IDPUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateOktaV2IDPUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p unauthorized response has a 2xx status code
func (o *UpdateOktaV2IDPUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p unauthorized response has a 3xx status code
func (o *UpdateOktaV2IDPUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p unauthorized response has a 4xx status code
func (o *UpdateOktaV2IDPUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p unauthorized response has a 5xx status code
func (o *UpdateOktaV2IDPUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p unauthorized response a status code equal to that given
func (o *UpdateOktaV2IDPUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update okta v2 Id p unauthorized response
func (o *UpdateOktaV2IDPUnauthorized) Code() int {
	return 401
}

func (o *UpdateOktaV2IDPUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPUnauthorized %s", 401, payload)
}

func (o *UpdateOktaV2IDPUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPUnauthorized %s", 401, payload)
}

func (o *UpdateOktaV2IDPUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPForbidden creates a UpdateOktaV2IDPForbidden with default headers values
func NewUpdateOktaV2IDPForbidden() *UpdateOktaV2IDPForbidden {
	return &UpdateOktaV2IDPForbidden{}
}

/*
UpdateOktaV2IDPForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateOktaV2IDPForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p forbidden response has a 2xx status code
func (o *UpdateOktaV2IDPForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p forbidden response has a 3xx status code
func (o *UpdateOktaV2IDPForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p forbidden response has a 4xx status code
func (o *UpdateOktaV2IDPForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p forbidden response has a 5xx status code
func (o *UpdateOktaV2IDPForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p forbidden response a status code equal to that given
func (o *UpdateOktaV2IDPForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update okta v2 Id p forbidden response
func (o *UpdateOktaV2IDPForbidden) Code() int {
	return 403
}

func (o *UpdateOktaV2IDPForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPForbidden %s", 403, payload)
}

func (o *UpdateOktaV2IDPForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPForbidden %s", 403, payload)
}

func (o *UpdateOktaV2IDPForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPNotFound creates a UpdateOktaV2IDPNotFound with default headers values
func NewUpdateOktaV2IDPNotFound() *UpdateOktaV2IDPNotFound {
	return &UpdateOktaV2IDPNotFound{}
}

/*
UpdateOktaV2IDPNotFound describes a response with status code 404, with default header values.

Not found
*/
type UpdateOktaV2IDPNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p not found response has a 2xx status code
func (o *UpdateOktaV2IDPNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p not found response has a 3xx status code
func (o *UpdateOktaV2IDPNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p not found response has a 4xx status code
func (o *UpdateOktaV2IDPNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p not found response has a 5xx status code
func (o *UpdateOktaV2IDPNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p not found response a status code equal to that given
func (o *UpdateOktaV2IDPNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update okta v2 Id p not found response
func (o *UpdateOktaV2IDPNotFound) Code() int {
	return 404
}

func (o *UpdateOktaV2IDPNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPNotFound %s", 404, payload)
}

func (o *UpdateOktaV2IDPNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPNotFound %s", 404, payload)
}

func (o *UpdateOktaV2IDPNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPUnprocessableEntity creates a UpdateOktaV2IDPUnprocessableEntity with default headers values
func NewUpdateOktaV2IDPUnprocessableEntity() *UpdateOktaV2IDPUnprocessableEntity {
	return &UpdateOktaV2IDPUnprocessableEntity{}
}

/*
UpdateOktaV2IDPUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type UpdateOktaV2IDPUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p unprocessable entity response has a 2xx status code
func (o *UpdateOktaV2IDPUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p unprocessable entity response has a 3xx status code
func (o *UpdateOktaV2IDPUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p unprocessable entity response has a 4xx status code
func (o *UpdateOktaV2IDPUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p unprocessable entity response has a 5xx status code
func (o *UpdateOktaV2IDPUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p unprocessable entity response a status code equal to that given
func (o *UpdateOktaV2IDPUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the update okta v2 Id p unprocessable entity response
func (o *UpdateOktaV2IDPUnprocessableEntity) Code() int {
	return 422
}

func (o *UpdateOktaV2IDPUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPUnprocessableEntity %s", 422, payload)
}

func (o *UpdateOktaV2IDPUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPUnprocessableEntity %s", 422, payload)
}

func (o *UpdateOktaV2IDPUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOktaV2IDPTooManyRequests creates a UpdateOktaV2IDPTooManyRequests with default headers values
func NewUpdateOktaV2IDPTooManyRequests() *UpdateOktaV2IDPTooManyRequests {
	return &UpdateOktaV2IDPTooManyRequests{}
}

/*
UpdateOktaV2IDPTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type UpdateOktaV2IDPTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this update okta v2 Id p too many requests response has a 2xx status code
func (o *UpdateOktaV2IDPTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update okta v2 Id p too many requests response has a 3xx status code
func (o *UpdateOktaV2IDPTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update okta v2 Id p too many requests response has a 4xx status code
func (o *UpdateOktaV2IDPTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this update okta v2 Id p too many requests response has a 5xx status code
func (o *UpdateOktaV2IDPTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this update okta v2 Id p too many requests response a status code equal to that given
func (o *UpdateOktaV2IDPTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the update okta v2 Id p too many requests response
func (o *UpdateOktaV2IDPTooManyRequests) Code() int {
	return 429
}

func (o *UpdateOktaV2IDPTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPTooManyRequests %s", 429, payload)
}

func (o *UpdateOktaV2IDPTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/okta_v2/{iid}][%d] updateOktaV2IdPTooManyRequests %s", 429, payload)
}

func (o *UpdateOktaV2IDPTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateOktaV2IDPTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
