// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// NewUpdateOktaIDPParams creates a new UpdateOktaIDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOktaIDPParams() *UpdateOktaIDPParams {
	return &UpdateOktaIDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOktaIDPParamsWithTimeout creates a new UpdateOktaIDPParams object
// with the ability to set a timeout on a request.
func NewUpdateOktaIDPParamsWithTimeout(timeout time.Duration) *UpdateOktaIDPParams {
	return &UpdateOktaIDPParams{
		timeout: timeout,
	}
}

// NewUpdateOktaIDPParamsWithContext creates a new UpdateOktaIDPParams object
// with the ability to set a context for a request.
func NewUpdateOktaIDPParamsWithContext(ctx context.Context) *UpdateOktaIDPParams {
	return &UpdateOktaIDPParams{
		Context: ctx,
	}
}

// NewUpdateOktaIDPParamsWithHTTPClient creates a new UpdateOktaIDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOktaIDPParamsWithHTTPClient(client *http.Client) *UpdateOktaIDPParams {
	return &UpdateOktaIDPParams{
		HTTPClient: client,
	}
}

/*
UpdateOktaIDPParams contains all the parameters to send to the API endpoint

	for the update okta ID p operation.

	Typically these are written to a http.Request.
*/
type UpdateOktaIDPParams struct {

	/* OktaIDP.

	   OktaIDP
	*/
	OktaIDP *models.OktaIDP

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Iid.

	   IDP id

	   Default: "default"
	*/
	Iid string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update okta ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOktaIDPParams) WithDefaults() *UpdateOktaIDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update okta ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOktaIDPParams) SetDefaults() {
	var (
		iidDefault = string("default")

		widDefault = string("default")
	)

	val := UpdateOktaIDPParams{
		Iid: iidDefault,
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update okta ID p params
func (o *UpdateOktaIDPParams) WithTimeout(timeout time.Duration) *UpdateOktaIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update okta ID p params
func (o *UpdateOktaIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update okta ID p params
func (o *UpdateOktaIDPParams) WithContext(ctx context.Context) *UpdateOktaIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update okta ID p params
func (o *UpdateOktaIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update okta ID p params
func (o *UpdateOktaIDPParams) WithHTTPClient(client *http.Client) *UpdateOktaIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update okta ID p params
func (o *UpdateOktaIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOktaIDP adds the oktaIDP to the update okta ID p params
func (o *UpdateOktaIDPParams) WithOktaIDP(oktaIDP *models.OktaIDP) *UpdateOktaIDPParams {
	o.SetOktaIDP(oktaIDP)
	return o
}

// SetOktaIDP adds the oktaIdP to the update okta ID p params
func (o *UpdateOktaIDPParams) SetOktaIDP(oktaIDP *models.OktaIDP) {
	o.OktaIDP = oktaIDP
}

// WithIfMatch adds the ifMatch to the update okta ID p params
func (o *UpdateOktaIDPParams) WithIfMatch(ifMatch *string) *UpdateOktaIDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the update okta ID p params
func (o *UpdateOktaIDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIid adds the iid to the update okta ID p params
func (o *UpdateOktaIDPParams) WithIid(iid string) *UpdateOktaIDPParams {
	o.SetIid(iid)
	return o
}

// SetIid adds the iid to the update okta ID p params
func (o *UpdateOktaIDPParams) SetIid(iid string) {
	o.Iid = iid
}

// WithWid adds the wid to the update okta ID p params
func (o *UpdateOktaIDPParams) WithWid(wid string) *UpdateOktaIDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the update okta ID p params
func (o *UpdateOktaIDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the update okta ID p params
func (o *UpdateOktaIDPParams) WithXCorrelationID(xCorrelationID *string) *UpdateOktaIDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the update okta ID p params
func (o *UpdateOktaIDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the update okta ID p params
func (o *UpdateOktaIDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *UpdateOktaIDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the update okta ID p params
func (o *UpdateOktaIDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOktaIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OktaIDP != nil {
		if err := r.SetBodyParam(o.OktaIDP); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param iid
	if err := r.SetPathParam("iid", o.Iid); err != nil {
		return err
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
