// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// UpdateWorkforceIDPReader is a Reader for the UpdateWorkforceIDP structure.
type UpdateWorkforceIDPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateWorkforceIDPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateWorkforceIDPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateWorkforceIDPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateWorkforceIDPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateWorkforceIDPForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateWorkforceIDPNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateWorkforceIDPUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateWorkforceIDPTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /servers/{wid}/idps/workforce/{iid}] updateWorkforceIDP", response, response.Code())
	}
}

// NewUpdateWorkforceIDPOK creates a UpdateWorkforceIDPOK with default headers values
func NewUpdateWorkforceIDPOK() *UpdateWorkforceIDPOK {
	return &UpdateWorkforceIDPOK{}
}

/*
UpdateWorkforceIDPOK describes a response with status code 200, with default header values.

WorkforceIDP
*/
type UpdateWorkforceIDPOK struct {
	Payload *models.WorkforceIDP
}

// IsSuccess returns true when this update workforce Id p o k response has a 2xx status code
func (o *UpdateWorkforceIDPOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update workforce Id p o k response has a 3xx status code
func (o *UpdateWorkforceIDPOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p o k response has a 4xx status code
func (o *UpdateWorkforceIDPOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update workforce Id p o k response has a 5xx status code
func (o *UpdateWorkforceIDPOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p o k response a status code equal to that given
func (o *UpdateWorkforceIDPOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update workforce Id p o k response
func (o *UpdateWorkforceIDPOK) Code() int {
	return 200
}

func (o *UpdateWorkforceIDPOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPOK %s", 200, payload)
}

func (o *UpdateWorkforceIDPOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPOK %s", 200, payload)
}

func (o *UpdateWorkforceIDPOK) GetPayload() *models.WorkforceIDP {
	return o.Payload
}

func (o *UpdateWorkforceIDPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WorkforceIDP)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPBadRequest creates a UpdateWorkforceIDPBadRequest with default headers values
func NewUpdateWorkforceIDPBadRequest() *UpdateWorkforceIDPBadRequest {
	return &UpdateWorkforceIDPBadRequest{}
}

/*
UpdateWorkforceIDPBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type UpdateWorkforceIDPBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p bad request response has a 2xx status code
func (o *UpdateWorkforceIDPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p bad request response has a 3xx status code
func (o *UpdateWorkforceIDPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p bad request response has a 4xx status code
func (o *UpdateWorkforceIDPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p bad request response has a 5xx status code
func (o *UpdateWorkforceIDPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p bad request response a status code equal to that given
func (o *UpdateWorkforceIDPBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update workforce Id p bad request response
func (o *UpdateWorkforceIDPBadRequest) Code() int {
	return 400
}

func (o *UpdateWorkforceIDPBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPBadRequest %s", 400, payload)
}

func (o *UpdateWorkforceIDPBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPBadRequest %s", 400, payload)
}

func (o *UpdateWorkforceIDPBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPUnauthorized creates a UpdateWorkforceIDPUnauthorized with default headers values
func NewUpdateWorkforceIDPUnauthorized() *UpdateWorkforceIDPUnauthorized {
	return &UpdateWorkforceIDPUnauthorized{}
}

/*
UpdateWorkforceIDPUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateWorkforceIDPUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p unauthorized response has a 2xx status code
func (o *UpdateWorkforceIDPUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p unauthorized response has a 3xx status code
func (o *UpdateWorkforceIDPUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p unauthorized response has a 4xx status code
func (o *UpdateWorkforceIDPUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p unauthorized response has a 5xx status code
func (o *UpdateWorkforceIDPUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p unauthorized response a status code equal to that given
func (o *UpdateWorkforceIDPUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update workforce Id p unauthorized response
func (o *UpdateWorkforceIDPUnauthorized) Code() int {
	return 401
}

func (o *UpdateWorkforceIDPUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPUnauthorized %s", 401, payload)
}

func (o *UpdateWorkforceIDPUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPUnauthorized %s", 401, payload)
}

func (o *UpdateWorkforceIDPUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPForbidden creates a UpdateWorkforceIDPForbidden with default headers values
func NewUpdateWorkforceIDPForbidden() *UpdateWorkforceIDPForbidden {
	return &UpdateWorkforceIDPForbidden{}
}

/*
UpdateWorkforceIDPForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateWorkforceIDPForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p forbidden response has a 2xx status code
func (o *UpdateWorkforceIDPForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p forbidden response has a 3xx status code
func (o *UpdateWorkforceIDPForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p forbidden response has a 4xx status code
func (o *UpdateWorkforceIDPForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p forbidden response has a 5xx status code
func (o *UpdateWorkforceIDPForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p forbidden response a status code equal to that given
func (o *UpdateWorkforceIDPForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update workforce Id p forbidden response
func (o *UpdateWorkforceIDPForbidden) Code() int {
	return 403
}

func (o *UpdateWorkforceIDPForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPForbidden %s", 403, payload)
}

func (o *UpdateWorkforceIDPForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPForbidden %s", 403, payload)
}

func (o *UpdateWorkforceIDPForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPNotFound creates a UpdateWorkforceIDPNotFound with default headers values
func NewUpdateWorkforceIDPNotFound() *UpdateWorkforceIDPNotFound {
	return &UpdateWorkforceIDPNotFound{}
}

/*
UpdateWorkforceIDPNotFound describes a response with status code 404, with default header values.

Not found
*/
type UpdateWorkforceIDPNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p not found response has a 2xx status code
func (o *UpdateWorkforceIDPNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p not found response has a 3xx status code
func (o *UpdateWorkforceIDPNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p not found response has a 4xx status code
func (o *UpdateWorkforceIDPNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p not found response has a 5xx status code
func (o *UpdateWorkforceIDPNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p not found response a status code equal to that given
func (o *UpdateWorkforceIDPNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update workforce Id p not found response
func (o *UpdateWorkforceIDPNotFound) Code() int {
	return 404
}

func (o *UpdateWorkforceIDPNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPNotFound %s", 404, payload)
}

func (o *UpdateWorkforceIDPNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPNotFound %s", 404, payload)
}

func (o *UpdateWorkforceIDPNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPUnprocessableEntity creates a UpdateWorkforceIDPUnprocessableEntity with default headers values
func NewUpdateWorkforceIDPUnprocessableEntity() *UpdateWorkforceIDPUnprocessableEntity {
	return &UpdateWorkforceIDPUnprocessableEntity{}
}

/*
UpdateWorkforceIDPUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type UpdateWorkforceIDPUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p unprocessable entity response has a 2xx status code
func (o *UpdateWorkforceIDPUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p unprocessable entity response has a 3xx status code
func (o *UpdateWorkforceIDPUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p unprocessable entity response has a 4xx status code
func (o *UpdateWorkforceIDPUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p unprocessable entity response has a 5xx status code
func (o *UpdateWorkforceIDPUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p unprocessable entity response a status code equal to that given
func (o *UpdateWorkforceIDPUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the update workforce Id p unprocessable entity response
func (o *UpdateWorkforceIDPUnprocessableEntity) Code() int {
	return 422
}

func (o *UpdateWorkforceIDPUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPUnprocessableEntity %s", 422, payload)
}

func (o *UpdateWorkforceIDPUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPUnprocessableEntity %s", 422, payload)
}

func (o *UpdateWorkforceIDPUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateWorkforceIDPTooManyRequests creates a UpdateWorkforceIDPTooManyRequests with default headers values
func NewUpdateWorkforceIDPTooManyRequests() *UpdateWorkforceIDPTooManyRequests {
	return &UpdateWorkforceIDPTooManyRequests{}
}

/*
UpdateWorkforceIDPTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type UpdateWorkforceIDPTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this update workforce Id p too many requests response has a 2xx status code
func (o *UpdateWorkforceIDPTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update workforce Id p too many requests response has a 3xx status code
func (o *UpdateWorkforceIDPTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update workforce Id p too many requests response has a 4xx status code
func (o *UpdateWorkforceIDPTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this update workforce Id p too many requests response has a 5xx status code
func (o *UpdateWorkforceIDPTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this update workforce Id p too many requests response a status code equal to that given
func (o *UpdateWorkforceIDPTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the update workforce Id p too many requests response
func (o *UpdateWorkforceIDPTooManyRequests) Code() int {
	return 429
}

func (o *UpdateWorkforceIDPTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPTooManyRequests %s", 429, payload)
}

func (o *UpdateWorkforceIDPTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /servers/{wid}/idps/workforce/{iid}][%d] updateWorkforceIdPTooManyRequests %s", 429, payload)
}

func (o *UpdateWorkforceIDPTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateWorkforceIDPTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
