// Code generated by go-swagger; DO NOT EDIT.

package idps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/system/models"
)

// NewUpdateActiveDirectoryIDPParams creates a new UpdateActiveDirectoryIDPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateActiveDirectoryIDPParams() *UpdateActiveDirectoryIDPParams {
	return &UpdateActiveDirectoryIDPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateActiveDirectoryIDPParamsWithTimeout creates a new UpdateActiveDirectoryIDPParams object
// with the ability to set a timeout on a request.
func NewUpdateActiveDirectoryIDPParamsWithTimeout(timeout time.Duration) *UpdateActiveDirectoryIDPParams {
	return &UpdateActiveDirectoryIDPParams{
		timeout: timeout,
	}
}

// NewUpdateActiveDirectoryIDPParamsWithContext creates a new UpdateActiveDirectoryIDPParams object
// with the ability to set a context for a request.
func NewUpdateActiveDirectoryIDPParamsWithContext(ctx context.Context) *UpdateActiveDirectoryIDPParams {
	return &UpdateActiveDirectoryIDPParams{
		Context: ctx,
	}
}

// NewUpdateActiveDirectoryIDPParamsWithHTTPClient creates a new UpdateActiveDirectoryIDPParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateActiveDirectoryIDPParamsWithHTTPClient(client *http.Client) *UpdateActiveDirectoryIDPParams {
	return &UpdateActiveDirectoryIDPParams{
		HTTPClient: client,
	}
}

/*
UpdateActiveDirectoryIDPParams contains all the parameters to send to the API endpoint

	for the update active directory ID p operation.

	Typically these are written to a http.Request.
*/
type UpdateActiveDirectoryIDPParams struct {

	/* ActiveDirectoryIDP.

	   ActiveDirectoryIDP
	*/
	ActiveDirectoryIDP *models.ActiveDirectoryIDP

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Iid.

	   IDP id

	   Default: "default"
	*/
	Iid string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update active directory ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateActiveDirectoryIDPParams) WithDefaults() *UpdateActiveDirectoryIDPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update active directory ID p params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateActiveDirectoryIDPParams) SetDefaults() {
	var (
		iidDefault = string("default")

		widDefault = string("default")
	)

	val := UpdateActiveDirectoryIDPParams{
		Iid: iidDefault,
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithTimeout(timeout time.Duration) *UpdateActiveDirectoryIDPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithContext(ctx context.Context) *UpdateActiveDirectoryIDPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithHTTPClient(client *http.Client) *UpdateActiveDirectoryIDPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActiveDirectoryIDP adds the activeDirectoryIDP to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithActiveDirectoryIDP(activeDirectoryIDP *models.ActiveDirectoryIDP) *UpdateActiveDirectoryIDPParams {
	o.SetActiveDirectoryIDP(activeDirectoryIDP)
	return o
}

// SetActiveDirectoryIDP adds the activeDirectoryIdP to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetActiveDirectoryIDP(activeDirectoryIDP *models.ActiveDirectoryIDP) {
	o.ActiveDirectoryIDP = activeDirectoryIDP
}

// WithIfMatch adds the ifMatch to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithIfMatch(ifMatch *string) *UpdateActiveDirectoryIDPParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIid adds the iid to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithIid(iid string) *UpdateActiveDirectoryIDPParams {
	o.SetIid(iid)
	return o
}

// SetIid adds the iid to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetIid(iid string) {
	o.Iid = iid
}

// WithWid adds the wid to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithWid(wid string) *UpdateActiveDirectoryIDPParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetWid(wid string) {
	o.Wid = wid
}

// WithXCorrelationID adds the xCorrelationID to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithXCorrelationID(xCorrelationID *string) *UpdateActiveDirectoryIDPParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) WithXIdempotencyKey(xIdempotencyKey *string) *UpdateActiveDirectoryIDPParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the update active directory ID p params
func (o *UpdateActiveDirectoryIDPParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateActiveDirectoryIDPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ActiveDirectoryIDP != nil {
		if err := r.SetBodyParam(o.ActiveDirectoryIDP); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param iid
	if err := r.SetPathParam("iid", o.Iid); err != nil {
		return err
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
