// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CaptchaDeployment CaptchaDeployment reports the deployment-wide captcha state without exposing any key.
//
// swagger:model CaptchaDeployment
type CaptchaDeployment struct {

	// captcha is enforced in this deployment; when false, tenant whitelists change nothing
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`

	// minimum reCAPTCHA v3 score accepted before falling back to v2
	Threshold float32 `json:"threshold,omitempty" yaml:"threshold,omitempty"`

	// a usable reCAPTCHA v2 site and secret key pair is configured
	V2Configured bool `json:"v2_configured,omitempty" yaml:"v2_configured,omitempty"`

	// a reCAPTCHA v3 site and secret key pair is configured
	V3Configured bool `json:"v3_configured,omitempty" yaml:"v3_configured,omitempty"`

	// identifier suffixes exempt for the whole deployment; a tenant whitelist replaces these
	Whitelist []string `json:"whitelist" yaml:"whitelist"`
}

// Validate validates this captcha deployment
func (m *CaptchaDeployment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this captcha deployment based on context it is used
func (m *CaptchaDeployment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CaptchaDeployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CaptchaDeployment) UnmarshalBinary(b []byte) error {
	var res CaptchaDeployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
