// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// GranteeType grantee type
//
// swagger:model GranteeType
type GranteeType string

// Validate validates this grantee type
func (m GranteeType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this grantee type based on context it is used
func (m GranteeType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
