// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewAuditEvent new audit event
//
// swagger:model NewAuditEvent
type NewAuditEvent struct {

	// Name of an action that was performed for a given event subject.
	// Example: created
	// Enum: ["authenticated","challenged","authorized","unauthorized","created","updated","deleted","generated","requested","confirmed","accepted","rejected","revoked","notified","issued","denied","granted","attempted","failed","succeeded","sent","not_sent","executed","calculated","reset_requested","reset_completed","add_requested","add_completed","added_to_group","removed_from_group"]
	Action string `json:"action,omitempty" yaml:"action,omitempty"`

	// Resource or entity that is a subject of a given audit event.
	// Example: client
	// Enum: ["request","gateway_request","gateway_policy","policy","client","credential","login","risk","post_authn","recovery","consent","client_consents","customer_consents","authorization_code","authorization_details","access_token","saml_assertion","scopes","claims","otp","user","schema","pool","password","bruteforce","dcr","script","role","task","jit","tokens","service","server","import","organization","otp_inspect","totp","device","webauthn","group"]
	EventSubject string `json:"event_subject,omitempty" yaml:"event_subject,omitempty"`

	// metadata
	Metadata *AuditEventMetadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Event payload.
	Payload interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`

	// Server ID.
	ServerID string `json:"server_id,omitempty" yaml:"server_id,omitempty"`

	// Tenant ID.
	TenantID string `json:"tenant_id,omitempty" yaml:"tenant_id,omitempty"`

	// Time when the event took place.
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
}

// Validate validates this new audit event
func (m *NewAuditEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEventSubject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var newAuditEventTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["authenticated","challenged","authorized","unauthorized","created","updated","deleted","generated","requested","confirmed","accepted","rejected","revoked","notified","issued","denied","granted","attempted","failed","succeeded","sent","not_sent","executed","calculated","reset_requested","reset_completed","add_requested","add_completed","added_to_group","removed_from_group"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		newAuditEventTypeActionPropEnum = append(newAuditEventTypeActionPropEnum, v)
	}
}

const (

	// NewAuditEventActionAuthenticated captures enum value "authenticated"
	NewAuditEventActionAuthenticated string = "authenticated"

	// NewAuditEventActionChallenged captures enum value "challenged"
	NewAuditEventActionChallenged string = "challenged"

	// NewAuditEventActionAuthorized captures enum value "authorized"
	NewAuditEventActionAuthorized string = "authorized"

	// NewAuditEventActionUnauthorized captures enum value "unauthorized"
	NewAuditEventActionUnauthorized string = "unauthorized"

	// NewAuditEventActionCreated captures enum value "created"
	NewAuditEventActionCreated string = "created"

	// NewAuditEventActionUpdated captures enum value "updated"
	NewAuditEventActionUpdated string = "updated"

	// NewAuditEventActionDeleted captures enum value "deleted"
	NewAuditEventActionDeleted string = "deleted"

	// NewAuditEventActionGenerated captures enum value "generated"
	NewAuditEventActionGenerated string = "generated"

	// NewAuditEventActionRequested captures enum value "requested"
	NewAuditEventActionRequested string = "requested"

	// NewAuditEventActionConfirmed captures enum value "confirmed"
	NewAuditEventActionConfirmed string = "confirmed"

	// NewAuditEventActionAccepted captures enum value "accepted"
	NewAuditEventActionAccepted string = "accepted"

	// NewAuditEventActionRejected captures enum value "rejected"
	NewAuditEventActionRejected string = "rejected"

	// NewAuditEventActionRevoked captures enum value "revoked"
	NewAuditEventActionRevoked string = "revoked"

	// NewAuditEventActionNotified captures enum value "notified"
	NewAuditEventActionNotified string = "notified"

	// NewAuditEventActionIssued captures enum value "issued"
	NewAuditEventActionIssued string = "issued"

	// NewAuditEventActionDenied captures enum value "denied"
	NewAuditEventActionDenied string = "denied"

	// NewAuditEventActionGranted captures enum value "granted"
	NewAuditEventActionGranted string = "granted"

	// NewAuditEventActionAttempted captures enum value "attempted"
	NewAuditEventActionAttempted string = "attempted"

	// NewAuditEventActionFailed captures enum value "failed"
	NewAuditEventActionFailed string = "failed"

	// NewAuditEventActionSucceeded captures enum value "succeeded"
	NewAuditEventActionSucceeded string = "succeeded"

	// NewAuditEventActionSent captures enum value "sent"
	NewAuditEventActionSent string = "sent"

	// NewAuditEventActionNotSent captures enum value "not_sent"
	NewAuditEventActionNotSent string = "not_sent"

	// NewAuditEventActionExecuted captures enum value "executed"
	NewAuditEventActionExecuted string = "executed"

	// NewAuditEventActionCalculated captures enum value "calculated"
	NewAuditEventActionCalculated string = "calculated"

	// NewAuditEventActionResetRequested captures enum value "reset_requested"
	NewAuditEventActionResetRequested string = "reset_requested"

	// NewAuditEventActionResetCompleted captures enum value "reset_completed"
	NewAuditEventActionResetCompleted string = "reset_completed"

	// NewAuditEventActionAddRequested captures enum value "add_requested"
	NewAuditEventActionAddRequested string = "add_requested"

	// NewAuditEventActionAddCompleted captures enum value "add_completed"
	NewAuditEventActionAddCompleted string = "add_completed"

	// NewAuditEventActionAddedToGroup captures enum value "added_to_group"
	NewAuditEventActionAddedToGroup string = "added_to_group"

	// NewAuditEventActionRemovedFromGroup captures enum value "removed_from_group"
	NewAuditEventActionRemovedFromGroup string = "removed_from_group"
)

// prop value enum
func (m *NewAuditEvent) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, newAuditEventTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NewAuditEvent) validateAction(formats strfmt.Registry) error {
	if swag.IsZero(m.Action) { // not required
		return nil
	}

	// value enum
	if err := m.validateActionEnum("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

var newAuditEventTypeEventSubjectPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["request","gateway_request","gateway_policy","policy","client","credential","login","risk","post_authn","recovery","consent","client_consents","customer_consents","authorization_code","authorization_details","access_token","saml_assertion","scopes","claims","otp","user","schema","pool","password","bruteforce","dcr","script","role","task","jit","tokens","service","server","import","organization","otp_inspect","totp","device","webauthn","group"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		newAuditEventTypeEventSubjectPropEnum = append(newAuditEventTypeEventSubjectPropEnum, v)
	}
}

const (

	// NewAuditEventEventSubjectRequest captures enum value "request"
	NewAuditEventEventSubjectRequest string = "request"

	// NewAuditEventEventSubjectGatewayRequest captures enum value "gateway_request"
	NewAuditEventEventSubjectGatewayRequest string = "gateway_request"

	// NewAuditEventEventSubjectGatewayPolicy captures enum value "gateway_policy"
	NewAuditEventEventSubjectGatewayPolicy string = "gateway_policy"

	// NewAuditEventEventSubjectPolicy captures enum value "policy"
	NewAuditEventEventSubjectPolicy string = "policy"

	// NewAuditEventEventSubjectClient captures enum value "client"
	NewAuditEventEventSubjectClient string = "client"

	// NewAuditEventEventSubjectCredential captures enum value "credential"
	NewAuditEventEventSubjectCredential string = "credential"

	// NewAuditEventEventSubjectLogin captures enum value "login"
	NewAuditEventEventSubjectLogin string = "login"

	// NewAuditEventEventSubjectRisk captures enum value "risk"
	NewAuditEventEventSubjectRisk string = "risk"

	// NewAuditEventEventSubjectPostAuthn captures enum value "post_authn"
	NewAuditEventEventSubjectPostAuthn string = "post_authn"

	// NewAuditEventEventSubjectRecovery captures enum value "recovery"
	NewAuditEventEventSubjectRecovery string = "recovery"

	// NewAuditEventEventSubjectConsent captures enum value "consent"
	NewAuditEventEventSubjectConsent string = "consent"

	// NewAuditEventEventSubjectClientConsents captures enum value "client_consents"
	NewAuditEventEventSubjectClientConsents string = "client_consents"

	// NewAuditEventEventSubjectCustomerConsents captures enum value "customer_consents"
	NewAuditEventEventSubjectCustomerConsents string = "customer_consents"

	// NewAuditEventEventSubjectAuthorizationCode captures enum value "authorization_code"
	NewAuditEventEventSubjectAuthorizationCode string = "authorization_code"

	// NewAuditEventEventSubjectAuthorizationDetails captures enum value "authorization_details"
	NewAuditEventEventSubjectAuthorizationDetails string = "authorization_details"

	// NewAuditEventEventSubjectAccessToken captures enum value "access_token"
	NewAuditEventEventSubjectAccessToken string = "access_token"

	// NewAuditEventEventSubjectSamlAssertion captures enum value "saml_assertion"
	NewAuditEventEventSubjectSamlAssertion string = "saml_assertion"

	// NewAuditEventEventSubjectScopes captures enum value "scopes"
	NewAuditEventEventSubjectScopes string = "scopes"

	// NewAuditEventEventSubjectClaims captures enum value "claims"
	NewAuditEventEventSubjectClaims string = "claims"

	// NewAuditEventEventSubjectOtp captures enum value "otp"
	NewAuditEventEventSubjectOtp string = "otp"

	// NewAuditEventEventSubjectUser captures enum value "user"
	NewAuditEventEventSubjectUser string = "user"

	// NewAuditEventEventSubjectSchema captures enum value "schema"
	NewAuditEventEventSubjectSchema string = "schema"

	// NewAuditEventEventSubjectPool captures enum value "pool"
	NewAuditEventEventSubjectPool string = "pool"

	// NewAuditEventEventSubjectPassword captures enum value "password"
	NewAuditEventEventSubjectPassword string = "password"

	// NewAuditEventEventSubjectBruteforce captures enum value "bruteforce"
	NewAuditEventEventSubjectBruteforce string = "bruteforce"

	// NewAuditEventEventSubjectDcr captures enum value "dcr"
	NewAuditEventEventSubjectDcr string = "dcr"

	// NewAuditEventEventSubjectScript captures enum value "script"
	NewAuditEventEventSubjectScript string = "script"

	// NewAuditEventEventSubjectRole captures enum value "role"
	NewAuditEventEventSubjectRole string = "role"

	// NewAuditEventEventSubjectTask captures enum value "task"
	NewAuditEventEventSubjectTask string = "task"

	// NewAuditEventEventSubjectJit captures enum value "jit"
	NewAuditEventEventSubjectJit string = "jit"

	// NewAuditEventEventSubjectTokens captures enum value "tokens"
	NewAuditEventEventSubjectTokens string = "tokens"

	// NewAuditEventEventSubjectService captures enum value "service"
	NewAuditEventEventSubjectService string = "service"

	// NewAuditEventEventSubjectServer captures enum value "server"
	NewAuditEventEventSubjectServer string = "server"

	// NewAuditEventEventSubjectImport captures enum value "import"
	NewAuditEventEventSubjectImport string = "import"

	// NewAuditEventEventSubjectOrganization captures enum value "organization"
	NewAuditEventEventSubjectOrganization string = "organization"

	// NewAuditEventEventSubjectOtpInspect captures enum value "otp_inspect"
	NewAuditEventEventSubjectOtpInspect string = "otp_inspect"

	// NewAuditEventEventSubjectTotp captures enum value "totp"
	NewAuditEventEventSubjectTotp string = "totp"

	// NewAuditEventEventSubjectDevice captures enum value "device"
	NewAuditEventEventSubjectDevice string = "device"

	// NewAuditEventEventSubjectWebauthn captures enum value "webauthn"
	NewAuditEventEventSubjectWebauthn string = "webauthn"

	// NewAuditEventEventSubjectGroup captures enum value "group"
	NewAuditEventEventSubjectGroup string = "group"
)

// prop value enum
func (m *NewAuditEvent) validateEventSubjectEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, newAuditEventTypeEventSubjectPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NewAuditEvent) validateEventSubject(formats strfmt.Registry) error {
	if swag.IsZero(m.EventSubject) { // not required
		return nil
	}

	// value enum
	if err := m.validateEventSubjectEnum("event_subject", "body", m.EventSubject); err != nil {
		return err
	}

	return nil
}

func (m *NewAuditEvent) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *NewAuditEvent) validateTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(m.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this new audit event based on the context it is used
func (m *NewAuditEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewAuditEvent) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {

		if swag.IsZero(m.Metadata) { // not required
			return nil
		}

		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewAuditEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewAuditEvent) UnmarshalBinary(b []byte) error {
	var res NewAuditEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
