// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PhoneProviderConfig PhoneProviderConfig represents a tenant's phone provider configuration.
//
// Providers is consulted only when Mode is custom. Active is derived from
// Mode (true when Mode is non-empty) and kept for back-compat reads.
//
// swagger:model PhoneProviderConfig
type PhoneProviderConfig struct {

	// active
	Active bool `json:"active,omitempty" yaml:"active,omitempty"`

	// mode
	// Required: true
	// Enum: ["built_in","custom"]
	Mode string `json:"mode" yaml:"mode"`

	// providers
	// Max Items: 5
	Providers []*PhoneProvider `json:"providers" yaml:"providers"`

	// tenant id
	TenantID string `json:"tenant_id,omitempty" yaml:"tenant_id,omitempty"`
}

// Validate validates this phone provider config
func (m *PhoneProviderConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProviders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var phoneProviderConfigTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["built_in","custom"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		phoneProviderConfigTypeModePropEnum = append(phoneProviderConfigTypeModePropEnum, v)
	}
}

const (

	// PhoneProviderConfigModeBuiltIn captures enum value "built_in"
	PhoneProviderConfigModeBuiltIn string = "built_in"

	// PhoneProviderConfigModeCustom captures enum value "custom"
	PhoneProviderConfigModeCustom string = "custom"
)

// prop value enum
func (m *PhoneProviderConfig) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, phoneProviderConfigTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PhoneProviderConfig) validateMode(formats strfmt.Registry) error {

	if err := validate.RequiredString("mode", "body", m.Mode); err != nil {
		return err
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *PhoneProviderConfig) validateProviders(formats strfmt.Registry) error {
	if swag.IsZero(m.Providers) { // not required
		return nil
	}

	iProvidersSize := int64(len(m.Providers))

	if err := validate.MaxItems("providers", "body", iProvidersSize, 5); err != nil {
		return err
	}

	for i := 0; i < len(m.Providers); i++ {
		if swag.IsZero(m.Providers[i]) { // not required
			continue
		}

		if m.Providers[i] != nil {
			if err := m.Providers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this phone provider config based on the context it is used
func (m *PhoneProviderConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProviders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PhoneProviderConfig) contextValidateProviders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Providers); i++ {

		if m.Providers[i] != nil {

			if swag.IsZero(m.Providers[i]) { // not required
				return nil
			}

			if err := m.Providers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PhoneProviderConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneProviderConfig) UnmarshalBinary(b []byte) error {
	var res PhoneProviderConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
