// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identity/models"
)

// PatchUserReader is a Reader for the PatchUser structure.
type PatchUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPatchUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPatchUserUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPatchUserTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /admin/pools/{ipID}/users/{userID}] patchUser", response, response.Code())
	}
}

// NewPatchUserOK creates a PatchUserOK with default headers values
func NewPatchUserOK() *PatchUserOK {
	return &PatchUserOK{}
}

/*
PatchUserOK describes a response with status code 200, with default header values.

User
*/
type PatchUserOK struct {

	/* The ETag HTTP header is an identifier for a specific version of a resource

	in:header

	     Format: etag
	*/
	Etag string

	/* Indicates that a 5xx error was caused by tenant-provided code

	in:header
	*/
	XExternalError string

	/* OpenTelemetry trace identifier

	in:header
	*/
	XTraceID string

	Payload *models.UserWithData
}

// IsSuccess returns true when this patch user o k response has a 2xx status code
func (o *PatchUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch user o k response has a 3xx status code
func (o *PatchUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user o k response has a 4xx status code
func (o *PatchUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch user o k response has a 5xx status code
func (o *PatchUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user o k response a status code equal to that given
func (o *PatchUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch user o k response
func (o *PatchUserOK) Code() int {
	return 200
}

func (o *PatchUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserOK %s", 200, payload)
}

func (o *PatchUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserOK %s", 200, payload)
}

func (o *PatchUserOK) GetPayload() *models.UserWithData {
	return o.Payload
}

func (o *PatchUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header etag
	hdrEtag := response.GetHeader("etag")

	if hdrEtag != "" {
		o.Etag = hdrEtag
	}

	// hydrates response header x-external-error
	hdrXExternalError := response.GetHeader("x-external-error")

	if hdrXExternalError != "" {
		o.XExternalError = hdrXExternalError
	}

	// hydrates response header x-trace-id
	hdrXTraceID := response.GetHeader("x-trace-id")

	if hdrXTraceID != "" {
		o.XTraceID = hdrXTraceID
	}

	o.Payload = new(models.UserWithData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserBadRequest creates a PatchUserBadRequest with default headers values
func NewPatchUserBadRequest() *PatchUserBadRequest {
	return &PatchUserBadRequest{}
}

/*
PatchUserBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PatchUserBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user bad request response has a 2xx status code
func (o *PatchUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user bad request response has a 3xx status code
func (o *PatchUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user bad request response has a 4xx status code
func (o *PatchUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user bad request response has a 5xx status code
func (o *PatchUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user bad request response a status code equal to that given
func (o *PatchUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch user bad request response
func (o *PatchUserBadRequest) Code() int {
	return 400
}

func (o *PatchUserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserBadRequest %s", 400, payload)
}

func (o *PatchUserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserBadRequest %s", 400, payload)
}

func (o *PatchUserBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserUnauthorized creates a PatchUserUnauthorized with default headers values
func NewPatchUserUnauthorized() *PatchUserUnauthorized {
	return &PatchUserUnauthorized{}
}

/*
PatchUserUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PatchUserUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user unauthorized response has a 2xx status code
func (o *PatchUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user unauthorized response has a 3xx status code
func (o *PatchUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user unauthorized response has a 4xx status code
func (o *PatchUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user unauthorized response has a 5xx status code
func (o *PatchUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user unauthorized response a status code equal to that given
func (o *PatchUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the patch user unauthorized response
func (o *PatchUserUnauthorized) Code() int {
	return 401
}

func (o *PatchUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserUnauthorized %s", 401, payload)
}

func (o *PatchUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserUnauthorized %s", 401, payload)
}

func (o *PatchUserUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserForbidden creates a PatchUserForbidden with default headers values
func NewPatchUserForbidden() *PatchUserForbidden {
	return &PatchUserForbidden{}
}

/*
PatchUserForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PatchUserForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user forbidden response has a 2xx status code
func (o *PatchUserForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user forbidden response has a 3xx status code
func (o *PatchUserForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user forbidden response has a 4xx status code
func (o *PatchUserForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user forbidden response has a 5xx status code
func (o *PatchUserForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user forbidden response a status code equal to that given
func (o *PatchUserForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the patch user forbidden response
func (o *PatchUserForbidden) Code() int {
	return 403
}

func (o *PatchUserForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserForbidden %s", 403, payload)
}

func (o *PatchUserForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserForbidden %s", 403, payload)
}

func (o *PatchUserForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserNotFound creates a PatchUserNotFound with default headers values
func NewPatchUserNotFound() *PatchUserNotFound {
	return &PatchUserNotFound{}
}

/*
PatchUserNotFound describes a response with status code 404, with default header values.

Not found
*/
type PatchUserNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user not found response has a 2xx status code
func (o *PatchUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user not found response has a 3xx status code
func (o *PatchUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user not found response has a 4xx status code
func (o *PatchUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user not found response has a 5xx status code
func (o *PatchUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user not found response a status code equal to that given
func (o *PatchUserNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the patch user not found response
func (o *PatchUserNotFound) Code() int {
	return 404
}

func (o *PatchUserNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserNotFound %s", 404, payload)
}

func (o *PatchUserNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserNotFound %s", 404, payload)
}

func (o *PatchUserNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserUnprocessableEntity creates a PatchUserUnprocessableEntity with default headers values
func NewPatchUserUnprocessableEntity() *PatchUserUnprocessableEntity {
	return &PatchUserUnprocessableEntity{}
}

/*
PatchUserUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type PatchUserUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user unprocessable entity response has a 2xx status code
func (o *PatchUserUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user unprocessable entity response has a 3xx status code
func (o *PatchUserUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user unprocessable entity response has a 4xx status code
func (o *PatchUserUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user unprocessable entity response has a 5xx status code
func (o *PatchUserUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user unprocessable entity response a status code equal to that given
func (o *PatchUserUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the patch user unprocessable entity response
func (o *PatchUserUnprocessableEntity) Code() int {
	return 422
}

func (o *PatchUserUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserUnprocessableEntity %s", 422, payload)
}

func (o *PatchUserUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserUnprocessableEntity %s", 422, payload)
}

func (o *PatchUserUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchUserTooManyRequests creates a PatchUserTooManyRequests with default headers values
func NewPatchUserTooManyRequests() *PatchUserTooManyRequests {
	return &PatchUserTooManyRequests{}
}

/*
PatchUserTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type PatchUserTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch user too many requests response has a 2xx status code
func (o *PatchUserTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch user too many requests response has a 3xx status code
func (o *PatchUserTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch user too many requests response has a 4xx status code
func (o *PatchUserTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch user too many requests response has a 5xx status code
func (o *PatchUserTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this patch user too many requests response a status code equal to that given
func (o *PatchUserTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the patch user too many requests response
func (o *PatchUserTooManyRequests) Code() int {
	return 429
}

func (o *PatchUserTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserTooManyRequests %s", 429, payload)
}

func (o *PatchUserTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /admin/pools/{ipID}/users/{userID}][%d] patchUserTooManyRequests %s", 429, payload)
}

func (o *PatchUserTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchUserTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
