// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// NewSystemSetDevicesParams creates a new SystemSetDevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemSetDevicesParams() *SystemSetDevicesParams {
	return &SystemSetDevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemSetDevicesParamsWithTimeout creates a new SystemSetDevicesParams object
// with the ability to set a timeout on a request.
func NewSystemSetDevicesParamsWithTimeout(timeout time.Duration) *SystemSetDevicesParams {
	return &SystemSetDevicesParams{
		timeout: timeout,
	}
}

// NewSystemSetDevicesParamsWithContext creates a new SystemSetDevicesParams object
// with the ability to set a context for a request.
func NewSystemSetDevicesParamsWithContext(ctx context.Context) *SystemSetDevicesParams {
	return &SystemSetDevicesParams{
		Context: ctx,
	}
}

// NewSystemSetDevicesParamsWithHTTPClient creates a new SystemSetDevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemSetDevicesParamsWithHTTPClient(client *http.Client) *SystemSetDevicesParams {
	return &SystemSetDevicesParams{
		HTTPClient: client,
	}
}

/*
SystemSetDevicesParams contains all the parameters to send to the API endpoint

	for the system set devices operation.

	Typically these are written to a http.Request.
*/
type SystemSetDevicesParams struct {

	// Devices.
	Devices *models.DevicesToSet

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	// IPID.
	IPID string

	// UserID.
	UserID string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system set devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSetDevicesParams) WithDefaults() *SystemSetDevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system set devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemSetDevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system set devices params
func (o *SystemSetDevicesParams) WithTimeout(timeout time.Duration) *SystemSetDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system set devices params
func (o *SystemSetDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system set devices params
func (o *SystemSetDevicesParams) WithContext(ctx context.Context) *SystemSetDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system set devices params
func (o *SystemSetDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system set devices params
func (o *SystemSetDevicesParams) WithHTTPClient(client *http.Client) *SystemSetDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system set devices params
func (o *SystemSetDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevices adds the devices to the system set devices params
func (o *SystemSetDevicesParams) WithDevices(devices *models.DevicesToSet) *SystemSetDevicesParams {
	o.SetDevices(devices)
	return o
}

// SetDevices adds the devices to the system set devices params
func (o *SystemSetDevicesParams) SetDevices(devices *models.DevicesToSet) {
	o.Devices = devices
}

// WithIfMatch adds the ifMatch to the system set devices params
func (o *SystemSetDevicesParams) WithIfMatch(ifMatch *string) *SystemSetDevicesParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the system set devices params
func (o *SystemSetDevicesParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIPID adds the iPID to the system set devices params
func (o *SystemSetDevicesParams) WithIPID(iPID string) *SystemSetDevicesParams {
	o.SetIPID(iPID)
	return o
}

// SetIPID adds the ipId to the system set devices params
func (o *SystemSetDevicesParams) SetIPID(iPID string) {
	o.IPID = iPID
}

// WithUserID adds the userID to the system set devices params
func (o *SystemSetDevicesParams) WithUserID(userID string) *SystemSetDevicesParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the system set devices params
func (o *SystemSetDevicesParams) SetUserID(userID string) {
	o.UserID = userID
}

// WithXCorrelationID adds the xCorrelationID to the system set devices params
func (o *SystemSetDevicesParams) WithXCorrelationID(xCorrelationID *string) *SystemSetDevicesParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the system set devices params
func (o *SystemSetDevicesParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the system set devices params
func (o *SystemSetDevicesParams) WithXIdempotencyKey(xIdempotencyKey *string) *SystemSetDevicesParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the system set devices params
func (o *SystemSetDevicesParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *SystemSetDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Devices != nil {
		if err := r.SetBodyParam(o.Devices); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param ipID
	if err := r.SetPathParam("ipID", o.IPID); err != nil {
		return err
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
