// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSystemPatchUserParams creates a new SystemPatchUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemPatchUserParams() *SystemPatchUserParams {
	return &SystemPatchUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemPatchUserParamsWithTimeout creates a new SystemPatchUserParams object
// with the ability to set a timeout on a request.
func NewSystemPatchUserParamsWithTimeout(timeout time.Duration) *SystemPatchUserParams {
	return &SystemPatchUserParams{
		timeout: timeout,
	}
}

// NewSystemPatchUserParamsWithContext creates a new SystemPatchUserParams object
// with the ability to set a context for a request.
func NewSystemPatchUserParamsWithContext(ctx context.Context) *SystemPatchUserParams {
	return &SystemPatchUserParams{
		Context: ctx,
	}
}

// NewSystemPatchUserParamsWithHTTPClient creates a new SystemPatchUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemPatchUserParamsWithHTTPClient(client *http.Client) *SystemPatchUserParams {
	return &SystemPatchUserParams{
		HTTPClient: client,
	}
}

/*
SystemPatchUserParams contains all the parameters to send to the API endpoint

	for the system patch user operation.

	Typically these are written to a http.Request.
*/
type SystemPatchUserParams struct {

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	// IPID.
	IPID string

	/* Patch.

	   Patch spec in format matching RFC Version
	*/
	Patch interface{}

	/* RfcVersion.

	   RFC version

	   Default: "7396"
	*/
	RfcVersion *string

	// UserID.
	UserID string

	/* XCorrelationID.

	   Unique identifier included in audit events for request tracking
	*/
	XCorrelationID *string

	/* XIdempotencyKey.

	   Key used to safely retry failed requests without duplicate processing
	*/
	XIdempotencyKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system patch user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemPatchUserParams) WithDefaults() *SystemPatchUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system patch user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemPatchUserParams) SetDefaults() {
	var (
		rfcVersionDefault = string("7396")
	)

	val := SystemPatchUserParams{
		RfcVersion: &rfcVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the system patch user params
func (o *SystemPatchUserParams) WithTimeout(timeout time.Duration) *SystemPatchUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system patch user params
func (o *SystemPatchUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system patch user params
func (o *SystemPatchUserParams) WithContext(ctx context.Context) *SystemPatchUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system patch user params
func (o *SystemPatchUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system patch user params
func (o *SystemPatchUserParams) WithHTTPClient(client *http.Client) *SystemPatchUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system patch user params
func (o *SystemPatchUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the system patch user params
func (o *SystemPatchUserParams) WithIfMatch(ifMatch *string) *SystemPatchUserParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the system patch user params
func (o *SystemPatchUserParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIPID adds the iPID to the system patch user params
func (o *SystemPatchUserParams) WithIPID(iPID string) *SystemPatchUserParams {
	o.SetIPID(iPID)
	return o
}

// SetIPID adds the ipId to the system patch user params
func (o *SystemPatchUserParams) SetIPID(iPID string) {
	o.IPID = iPID
}

// WithPatch adds the patch to the system patch user params
func (o *SystemPatchUserParams) WithPatch(patch interface{}) *SystemPatchUserParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the system patch user params
func (o *SystemPatchUserParams) SetPatch(patch interface{}) {
	o.Patch = patch
}

// WithRfcVersion adds the rfcVersion to the system patch user params
func (o *SystemPatchUserParams) WithRfcVersion(rfcVersion *string) *SystemPatchUserParams {
	o.SetRfcVersion(rfcVersion)
	return o
}

// SetRfcVersion adds the rfcVersion to the system patch user params
func (o *SystemPatchUserParams) SetRfcVersion(rfcVersion *string) {
	o.RfcVersion = rfcVersion
}

// WithUserID adds the userID to the system patch user params
func (o *SystemPatchUserParams) WithUserID(userID string) *SystemPatchUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the system patch user params
func (o *SystemPatchUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WithXCorrelationID adds the xCorrelationID to the system patch user params
func (o *SystemPatchUserParams) WithXCorrelationID(xCorrelationID *string) *SystemPatchUserParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the system patch user params
func (o *SystemPatchUserParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WithXIdempotencyKey adds the xIdempotencyKey to the system patch user params
func (o *SystemPatchUserParams) WithXIdempotencyKey(xIdempotencyKey *string) *SystemPatchUserParams {
	o.SetXIdempotencyKey(xIdempotencyKey)
	return o
}

// SetXIdempotencyKey adds the xIdempotencyKey to the system patch user params
func (o *SystemPatchUserParams) SetXIdempotencyKey(xIdempotencyKey *string) {
	o.XIdempotencyKey = xIdempotencyKey
}

// WriteToRequest writes these params to a swagger request
func (o *SystemPatchUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param ipID
	if err := r.SetPathParam("ipID", o.IPID); err != nil {
		return err
	}
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	if o.RfcVersion != nil {

		// query param rfc_version
		var qrRfcVersion string

		if o.RfcVersion != nil {
			qrRfcVersion = *o.RfcVersion
		}
		qRfcVersion := qrRfcVersion
		if qRfcVersion != "" {

			if err := r.SetQueryParam("rfc_version", qRfcVersion); err != nil {
				return err
			}
		}
	}

	// path param userID
	if err := r.SetPathParam("userID", o.UserID); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if o.XIdempotencyKey != nil {

		// header param x-idempotency-key
		if err := r.SetHeaderParam("x-idempotency-key", *o.XIdempotencyKey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
