// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationMembershipDeniedAuditPayload application membership denied audit payload
//
// swagger:model ApplicationMembershipDeniedAuditPayload
type ApplicationMembershipDeniedAuditPayload struct {

	// app workspace id
	AppWorkspaceID string `json:"app_workspace_id,omitempty" yaml:"app_workspace_id,omitempty"`

	// client id
	ClientID string `json:"client_id,omitempty" yaml:"client_id,omitempty"`

	// gate
	Gate EnforcementGate `json:"gate,omitempty" yaml:"gate,omitempty"`

	// Absent for pool-less subjects, which reach the gate legitimately.
	IdentityPoolID string `json:"identity_pool_id,omitempty" yaml:"identity_pool_id,omitempty"`

	// organization id
	OrganizationID string `json:"organization_id,omitempty" yaml:"organization_id,omitempty"`

	// reason
	Reason DenialReason `json:"reason,omitempty" yaml:"reason,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty" yaml:"user_id,omitempty"`
}

// Validate validates this application membership denied audit payload
func (m *ApplicationMembershipDeniedAuditPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicationMembershipDeniedAuditPayload) validateGate(formats strfmt.Registry) error {
	if swag.IsZero(m.Gate) { // not required
		return nil
	}

	if err := m.Gate.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("gate")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("gate")
		}
		return err
	}

	return nil
}

func (m *ApplicationMembershipDeniedAuditPayload) validateReason(formats strfmt.Registry) error {
	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	if err := m.Reason.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("reason")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("reason")
		}
		return err
	}

	return nil
}

// ContextValidate validate this application membership denied audit payload based on the context it is used
func (m *ApplicationMembershipDeniedAuditPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReason(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicationMembershipDeniedAuditPayload) contextValidateGate(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Gate) { // not required
		return nil
	}

	if err := m.Gate.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("gate")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("gate")
		}
		return err
	}

	return nil
}

func (m *ApplicationMembershipDeniedAuditPayload) contextValidateReason(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	if err := m.Reason.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("reason")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("reason")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationMembershipDeniedAuditPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationMembershipDeniedAuditPayload) UnmarshalBinary(b []byte) error {
	var res ApplicationMembershipDeniedAuditPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
