// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Insight insight
//
// swagger:model Insight
type Insight struct {

	// Description
	Desc string `json:"desc,omitempty" yaml:"desc,omitempty"`

	// Display name
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
}

// Validate validates this insight
func (m *Insight) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this insight based on context it is used
func (m *Insight) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Insight) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Insight) UnmarshalBinary(b []byte) error {
	var res Insight
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
