// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SoftwareStatementSettings software statement settings
//
// swagger:model SoftwareStatementSettings
type SoftwareStatementSettings struct {

	// Accepts registrations without a software statement
	//
	// If enabled, the registration endpoint no longer requires a software statement, but still
	// validates and applies one whenever a client presents it. Clients that register with a
	// software statement are distinguished by a non-empty `software_statement_payload`.
	//
	// Requires `enable_trust_anchor` to be on, as the trust anchor keys verify a presented
	// software statement.
	Optional bool `json:"optional,omitempty" yaml:"optional,omitempty"`
}

// Validate validates this software statement settings
func (m *SoftwareStatementSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this software statement settings based on context it is used
func (m *SoftwareStatementSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SoftwareStatementSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SoftwareStatementSettings) UnmarshalBinary(b []byte) error {
	var res SoftwareStatementSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
