// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Translation Translation
//
// Returns translations for a specific locale.
// It might include built-in translation, custom translation, and whether the locale is enabled.
//
// swagger:model Translation
type Translation struct {

	// built in translation
	BuiltInTranslation *BuiltInTranslation `json:"built_in_translation,omitempty" yaml:"built_in_translation,omitempty"`

	// custom translation
	CustomTranslation *CustomTranslation `json:"custom_translation,omitempty" yaml:"custom_translation,omitempty"`

	// When enabled, trnslations for this locale are available, when disabled the whole locale is disabled and no translations are available.
	// In case there is no built-in translation for this locale and the overwritten translation is not set, the locale is not active.
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`

	// Locale for which the translations are provided.
	// Required: true
	Locale string `json:"locale" yaml:"locale"`
}

// Validate validates this translation
func (m *Translation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuiltInTranslation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomTranslation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Translation) validateBuiltInTranslation(formats strfmt.Registry) error {
	if swag.IsZero(m.BuiltInTranslation) { // not required
		return nil
	}

	if m.BuiltInTranslation != nil {
		if err := m.BuiltInTranslation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("built_in_translation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("built_in_translation")
			}
			return err
		}
	}

	return nil
}

func (m *Translation) validateCustomTranslation(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomTranslation) { // not required
		return nil
	}

	if m.CustomTranslation != nil {
		if err := m.CustomTranslation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("custom_translation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("custom_translation")
			}
			return err
		}
	}

	return nil
}

func (m *Translation) validateLocale(formats strfmt.Registry) error {

	if err := validate.RequiredString("locale", "body", m.Locale); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this translation based on the context it is used
func (m *Translation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuiltInTranslation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCustomTranslation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Translation) contextValidateBuiltInTranslation(ctx context.Context, formats strfmt.Registry) error {

	if m.BuiltInTranslation != nil {

		if swag.IsZero(m.BuiltInTranslation) { // not required
			return nil
		}

		if err := m.BuiltInTranslation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("built_in_translation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("built_in_translation")
			}
			return err
		}
	}

	return nil
}

func (m *Translation) contextValidateCustomTranslation(ctx context.Context, formats strfmt.Registry) error {

	if m.CustomTranslation != nil {

		if swag.IsZero(m.CustomTranslation) { // not required
			return nil
		}

		if err := m.CustomTranslation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("custom_translation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("custom_translation")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Translation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Translation) UnmarshalBinary(b []byte) error {
	var res Translation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
