// Code generated by go-swagger; DO NOT EDIT.

package captcha

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCaptchaParams creates a new GetCaptchaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCaptchaParams() *GetCaptchaParams {
	return &GetCaptchaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCaptchaParamsWithTimeout creates a new GetCaptchaParams object
// with the ability to set a timeout on a request.
func NewGetCaptchaParamsWithTimeout(timeout time.Duration) *GetCaptchaParams {
	return &GetCaptchaParams{
		timeout: timeout,
	}
}

// NewGetCaptchaParamsWithContext creates a new GetCaptchaParams object
// with the ability to set a context for a request.
func NewGetCaptchaParamsWithContext(ctx context.Context) *GetCaptchaParams {
	return &GetCaptchaParams{
		Context: ctx,
	}
}

// NewGetCaptchaParamsWithHTTPClient creates a new GetCaptchaParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCaptchaParamsWithHTTPClient(client *http.Client) *GetCaptchaParams {
	return &GetCaptchaParams{
		HTTPClient: client,
	}
}

/*
GetCaptchaParams contains all the parameters to send to the API endpoint

	for the get captcha operation.

	Typically these are written to a http.Request.
*/
type GetCaptchaParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get captcha params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCaptchaParams) WithDefaults() *GetCaptchaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get captcha params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCaptchaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get captcha params
func (o *GetCaptchaParams) WithTimeout(timeout time.Duration) *GetCaptchaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get captcha params
func (o *GetCaptchaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get captcha params
func (o *GetCaptchaParams) WithContext(ctx context.Context) *GetCaptchaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get captcha params
func (o *GetCaptchaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get captcha params
func (o *GetCaptchaParams) WithHTTPClient(client *http.Client) *GetCaptchaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get captcha params
func (o *GetCaptchaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCaptchaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
