// Code generated by go-swagger; DO NOT EDIT.

package captcha

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/root/models"
)

// SetTenantCaptchaReader is a Reader for the SetTenantCaptcha structure.
type SetTenantCaptchaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetTenantCaptchaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetTenantCaptchaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetTenantCaptchaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSetTenantCaptchaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetTenantCaptchaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetTenantCaptchaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSetTenantCaptchaUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSetTenantCaptchaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/admin/tenants/{tid}/captcha] setTenantCaptcha", response, response.Code())
	}
}

// NewSetTenantCaptchaOK creates a SetTenantCaptchaOK with default headers values
func NewSetTenantCaptchaOK() *SetTenantCaptchaOK {
	return &SetTenantCaptchaOK{}
}

/*
SetTenantCaptchaOK describes a response with status code 200, with default header values.

Tenant captcha settings
*/
type SetTenantCaptchaOK struct {
	Payload *models.CaptchaSettings
}

// IsSuccess returns true when this set tenant captcha o k response has a 2xx status code
func (o *SetTenantCaptchaOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set tenant captcha o k response has a 3xx status code
func (o *SetTenantCaptchaOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha o k response has a 4xx status code
func (o *SetTenantCaptchaOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set tenant captcha o k response has a 5xx status code
func (o *SetTenantCaptchaOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha o k response a status code equal to that given
func (o *SetTenantCaptchaOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set tenant captcha o k response
func (o *SetTenantCaptchaOK) Code() int {
	return 200
}

func (o *SetTenantCaptchaOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaOK %s", 200, payload)
}

func (o *SetTenantCaptchaOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaOK %s", 200, payload)
}

func (o *SetTenantCaptchaOK) GetPayload() *models.CaptchaSettings {
	return o.Payload
}

func (o *SetTenantCaptchaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CaptchaSettings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaBadRequest creates a SetTenantCaptchaBadRequest with default headers values
func NewSetTenantCaptchaBadRequest() *SetTenantCaptchaBadRequest {
	return &SetTenantCaptchaBadRequest{}
}

/*
SetTenantCaptchaBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SetTenantCaptchaBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha bad request response has a 2xx status code
func (o *SetTenantCaptchaBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha bad request response has a 3xx status code
func (o *SetTenantCaptchaBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha bad request response has a 4xx status code
func (o *SetTenantCaptchaBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha bad request response has a 5xx status code
func (o *SetTenantCaptchaBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha bad request response a status code equal to that given
func (o *SetTenantCaptchaBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set tenant captcha bad request response
func (o *SetTenantCaptchaBadRequest) Code() int {
	return 400
}

func (o *SetTenantCaptchaBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaBadRequest %s", 400, payload)
}

func (o *SetTenantCaptchaBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaBadRequest %s", 400, payload)
}

func (o *SetTenantCaptchaBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaUnauthorized creates a SetTenantCaptchaUnauthorized with default headers values
func NewSetTenantCaptchaUnauthorized() *SetTenantCaptchaUnauthorized {
	return &SetTenantCaptchaUnauthorized{}
}

/*
SetTenantCaptchaUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SetTenantCaptchaUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha unauthorized response has a 2xx status code
func (o *SetTenantCaptchaUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha unauthorized response has a 3xx status code
func (o *SetTenantCaptchaUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha unauthorized response has a 4xx status code
func (o *SetTenantCaptchaUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha unauthorized response has a 5xx status code
func (o *SetTenantCaptchaUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha unauthorized response a status code equal to that given
func (o *SetTenantCaptchaUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the set tenant captcha unauthorized response
func (o *SetTenantCaptchaUnauthorized) Code() int {
	return 401
}

func (o *SetTenantCaptchaUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaUnauthorized %s", 401, payload)
}

func (o *SetTenantCaptchaUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaUnauthorized %s", 401, payload)
}

func (o *SetTenantCaptchaUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaForbidden creates a SetTenantCaptchaForbidden with default headers values
func NewSetTenantCaptchaForbidden() *SetTenantCaptchaForbidden {
	return &SetTenantCaptchaForbidden{}
}

/*
SetTenantCaptchaForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SetTenantCaptchaForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha forbidden response has a 2xx status code
func (o *SetTenantCaptchaForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha forbidden response has a 3xx status code
func (o *SetTenantCaptchaForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha forbidden response has a 4xx status code
func (o *SetTenantCaptchaForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha forbidden response has a 5xx status code
func (o *SetTenantCaptchaForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha forbidden response a status code equal to that given
func (o *SetTenantCaptchaForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the set tenant captcha forbidden response
func (o *SetTenantCaptchaForbidden) Code() int {
	return 403
}

func (o *SetTenantCaptchaForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaForbidden %s", 403, payload)
}

func (o *SetTenantCaptchaForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaForbidden %s", 403, payload)
}

func (o *SetTenantCaptchaForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaNotFound creates a SetTenantCaptchaNotFound with default headers values
func NewSetTenantCaptchaNotFound() *SetTenantCaptchaNotFound {
	return &SetTenantCaptchaNotFound{}
}

/*
SetTenantCaptchaNotFound describes a response with status code 404, with default header values.

Not found
*/
type SetTenantCaptchaNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha not found response has a 2xx status code
func (o *SetTenantCaptchaNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha not found response has a 3xx status code
func (o *SetTenantCaptchaNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha not found response has a 4xx status code
func (o *SetTenantCaptchaNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha not found response has a 5xx status code
func (o *SetTenantCaptchaNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha not found response a status code equal to that given
func (o *SetTenantCaptchaNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the set tenant captcha not found response
func (o *SetTenantCaptchaNotFound) Code() int {
	return 404
}

func (o *SetTenantCaptchaNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaNotFound %s", 404, payload)
}

func (o *SetTenantCaptchaNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaNotFound %s", 404, payload)
}

func (o *SetTenantCaptchaNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaUnprocessableEntity creates a SetTenantCaptchaUnprocessableEntity with default headers values
func NewSetTenantCaptchaUnprocessableEntity() *SetTenantCaptchaUnprocessableEntity {
	return &SetTenantCaptchaUnprocessableEntity{}
}

/*
SetTenantCaptchaUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type SetTenantCaptchaUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha unprocessable entity response has a 2xx status code
func (o *SetTenantCaptchaUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha unprocessable entity response has a 3xx status code
func (o *SetTenantCaptchaUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha unprocessable entity response has a 4xx status code
func (o *SetTenantCaptchaUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha unprocessable entity response has a 5xx status code
func (o *SetTenantCaptchaUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha unprocessable entity response a status code equal to that given
func (o *SetTenantCaptchaUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the set tenant captcha unprocessable entity response
func (o *SetTenantCaptchaUnprocessableEntity) Code() int {
	return 422
}

func (o *SetTenantCaptchaUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaUnprocessableEntity %s", 422, payload)
}

func (o *SetTenantCaptchaUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaUnprocessableEntity %s", 422, payload)
}

func (o *SetTenantCaptchaUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTenantCaptchaTooManyRequests creates a SetTenantCaptchaTooManyRequests with default headers values
func NewSetTenantCaptchaTooManyRequests() *SetTenantCaptchaTooManyRequests {
	return &SetTenantCaptchaTooManyRequests{}
}

/*
SetTenantCaptchaTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type SetTenantCaptchaTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this set tenant captcha too many requests response has a 2xx status code
func (o *SetTenantCaptchaTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tenant captcha too many requests response has a 3xx status code
func (o *SetTenantCaptchaTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tenant captcha too many requests response has a 4xx status code
func (o *SetTenantCaptchaTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tenant captcha too many requests response has a 5xx status code
func (o *SetTenantCaptchaTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this set tenant captcha too many requests response a status code equal to that given
func (o *SetTenantCaptchaTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the set tenant captcha too many requests response
func (o *SetTenantCaptchaTooManyRequests) Code() int {
	return 429
}

func (o *SetTenantCaptchaTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaTooManyRequests %s", 429, payload)
}

func (o *SetTenantCaptchaTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/admin/tenants/{tid}/captcha][%d] setTenantCaptchaTooManyRequests %s", 429, payload)
}

func (o *SetTenantCaptchaTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetTenantCaptchaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
