// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SAIDPSettings s a ID p settings
//
// swagger:model SAIDPSettings
type SAIDPSettings struct {

	// organization
	Organization string `json:"organization,omitempty" yaml:"organization,omitempty"`
}

// Validate validates this s a ID p settings
func (m *SAIDPSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this s a ID p settings based on context it is used
func (m *SAIDPSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SAIDPSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SAIDPSettings) UnmarshalBinary(b []byte) error {
	var res SAIDPSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
