// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VonagePhoneProvider VonagePhoneProvider holds Vonage-specific configuration. From and VoiceFrom
// are orthogonal: From is the SMS sender (alpha or E.164), VoiceFrom is the
// E.164 caller ID for voice. Required when voice is enabled.
//
// swagger:model VonagePhoneProvider
type VonagePhoneProvider struct {

	// api key
	// Required: true
	APIKey string `json:"api_key" yaml:"api_key"`

	// api secret
	// Required: true
	APISecret string `json:"api_secret" yaml:"api_secret"`

	// Vonage Application ID for voice API (optional — only needed for voice calls).
	ApplicationID string `json:"application_id,omitempty" yaml:"application_id,omitempty"`

	// When true, do not push a per-call delivery callback URL to Vonage.
	// Use this if your Vonage account is pre-configured with a webhook URL
	// you manage yourself. Applies to both SMS and voice.
	DisableDeliveryCallbackURL bool `json:"disable_delivery_callback_url,omitempty" yaml:"disable_delivery_callback_url,omitempty"`

	// from
	// Required: true
	From string `json:"from" yaml:"from"`

	// PEM-encoded RSA private key for voice API JWT auth (optional — only needed for voice calls).
	PrivateKey string `json:"private_key,omitempty" yaml:"private_key,omitempty"`

	// Vonage account signature secret for webhook JWT verification (optional — from Dashboard → Settings).
	SignatureSecret string `json:"signature_secret,omitempty" yaml:"signature_secret,omitempty"`

	// E.164 caller ID for voice calls (required when voice is enabled).
	VoiceFrom string `json:"voice_from,omitempty" yaml:"voice_from,omitempty"`
}

// Validate validates this vonage phone provider
func (m *VonagePhoneProvider) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAPISecret(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VonagePhoneProvider) validateAPIKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("api_key", "body", m.APIKey); err != nil {
		return err
	}

	return nil
}

func (m *VonagePhoneProvider) validateAPISecret(formats strfmt.Registry) error {

	if err := validate.RequiredString("api_secret", "body", m.APISecret); err != nil {
		return err
	}

	return nil
}

func (m *VonagePhoneProvider) validateFrom(formats strfmt.Registry) error {

	if err := validate.RequiredString("from", "body", m.From); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this vonage phone provider based on context it is used
func (m *VonagePhoneProvider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VonagePhoneProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VonagePhoneProvider) UnmarshalBinary(b []byte) error {
	var res VonagePhoneProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
